KShowmail: AccountViewItem Class Reference
AccountViewItem Class Reference
This class is used by AccountViewModel to hold a list of the accounts.
#include <accountviewitem.h>
Public Member Functions
AccountViewItem (bool active, const QString &name, const QString &server, const QString &user, int numberMails, long totalSize, QPointer< Account > account)
Contructor.
bool isActive () const
Returns whether the account is active.
QString getName () const
Returns the account name.
QString getServer () const
Returns ther server host name.
QString getUser () const
Returns the user.
int getNumberMails () const
Returns the number of mails.
QString getTotalSizeUnit () const
Returns the total size of mails with appended unit.
long getTotalSize () const
Returns the total size of mails.
QPointer< Account > getAccount () const
Returns the pointer to the account.
int compare (const AccountViewItem &other, AccountSort_Type property)
Compares this account with other and returns an integer less than, equal to, or greater than zero if this account is less than, equal to, or greater than other.
Private Attributes
bool active
true - the account is active
QString name
account name
QString server
server
QString user
user
int numberMails
number of mails
long totalSize
total size of mails, inclusive unit
QPointer< Account > account
pointer to the account
Detailed Description
This class is used by AccountViewModel to hold a list of the accounts.
It can't use a list of pointers to a account because this pointers can be invalid for a short time after an account was removed. When the account view refreshes in this time the app crashed.
Definition at line 37 of file accountviewitem.h.
Constructor & Destructor Documentation
AccountViewItem::AccountViewItem (bool active, const QString & name, const QString & server, const QString & user, int numberMails, long totalSize, QPointer< Account > account)
Contructor.
Parameters:
active true - the account is active; false - the account is not active
name Name of the account
server server
user user
numberMails number of mails
totalSize total size of all mails
account pointer to the associated account
Definition at line 23 of file accountviewitem.cpp.
Member Function Documentation
bool AccountViewItem::isActive () const
Returns whether the account is active.
Returns:
true - account is active; false - account isn't active
Definition at line 28 of file accountviewitem.cpp.
References active.
Referenced by compare(), and AccountViewModel::data().
QString AccountViewItem::getName () const
Returns the account name.
Returns:
account name
Definition at line 33 of file accountviewitem.cpp.
References name.
Referenced by compare(), and AccountViewModel::data().
QString AccountViewItem::getServer () const
Returns ther server host name.
Returns:
server host
Definition at line 38 of file accountviewitem.cpp.
References server.
Referenced by compare(), and AccountViewModel::data().
QString AccountViewItem::getUser () const
Returns the user.
Returns:
user
Definition at line 75 of file accountviewitem.cpp.
References user.
Referenced by compare(), and AccountViewModel::data().
int AccountViewItem::getNumberMails () const
Returns the number of mails.
Returns:
number of mails
Definition at line 48 of file accountviewitem.cpp.
References numberMails.
Referenced by compare(), and AccountViewModel::data().
QString AccountViewItem::getTotalSizeUnit () const
Returns the total size of mails with appended unit.
Returns:
total size of mails
Definition at line 53 of file accountviewitem.cpp.
References totalSize.
Referenced by AccountViewModel::data().
long int AccountViewItem::getTotalSize () const
Returns the total size of mails.
Returns:
total size of mails
Definition at line 135 of file accountviewitem.cpp.
References totalSize.
Referenced by compare().
QPointer< Account > AccountViewItem::getAccount () const
Returns the pointer to the account.
Returns:
pointer to the associated account
Definition at line 43 of file accountviewitem.cpp.
References account.
Referenced by AccountViewModel::getAccount(), and AccountViewModel::setData().
int AccountViewItem::compare (const AccountViewItem & other, AccountSort_Type property)
Compares this account with other and returns an integer less than, equal to, or greater than zero if this account is less than, equal to, or greater than other.
Parameters:
other other account
property the account property which will be compared
Definition at line 80 of file accountviewitem.cpp.
References Types::AccSortActive, Types::AccSortName, Types::AccSortNrMess, Types::AccSortServer, Types::AccSortSize, Types::AccSortUser, getName(), getNumberMails(), getServer(), getTotalSize(), getUser(), and isActive().
Referenced by AccountViewModel::sort().
Member Data Documentation
bool AccountViewItem::active [private]
true - the account is active
Definition at line 117 of file accountviewitem.h.
Referenced by isActive().
QString AccountViewItem::name [private]
account name
Definition at line 122 of file accountviewitem.h.
Referenced by getName().
QString AccountViewItem::server [private]
server
Definition at line 127 of file accountviewitem.h.
Referenced by getServer().
QString AccountViewItem::user [private]
user
Definition at line 132 of file accountviewitem.h.
Referenced by getUser().
int AccountViewItem::numberMails [private]
number of mails
Definition at line 137 of file accountviewitem.h.
Referenced by getNumberMails().
long AccountViewItem::totalSize [private]
total size of mails, inclusive unit
Definition at line 142 of file accountviewitem.h.
Referenced by getTotalSize(), and getTotalSizeUnit().
QPointer<Account> AccountViewItem::account [private]
pointer to the account
Definition at line 147 of file accountviewitem.h.
Referenced by getAccount().
The documentation for this class was generated from the following files:
src/accountviewitem.h
src/accountviewitem.cpp