KShowmail: FilterLog Class Reference
FilterLog Class Reference
This is the log of the filters.
#include <filterlog.h>
Public Member Functions
FilterLog ()
~FilterLog ()
void addDeletedMail (const KDateTime &dateTime, const QString &sender, const QString &account, const QString &subject)
void addMovedMail (const KDateTime &dateTime, const QString &sender, const QString &account, const QString &subject, const QString &mailbox)
void print ()
void clearDeletedMailsLog ()
void clearMovedMailsLog ()
void save ()
void load ()
LogEntryList getDeletedMails ()
LogEntryList getMovedMails ()
void loadSetup ()
int numberDeletedMails ()
int numberMovedMails ()
Protected Member Functions
void addEntry (FilterAction_Type action, const KDateTime &dateTime, const QString &sender, const QString &account, const QString &subject, const QString &mailbox=QString())
Private Types
enum { exit, days }
Private Attributes
KSharedConfigPtr config
LogEntryList listDeletedMails
LogEntryList listMovedMails
bool logDeletedMails
bool logMovedMails
enum FilterLog:: { ... } deletedMailsStorageMode
unsigned int daysStoreDeletedMails
Detailed Description
This is the log of the filters.
It holds two lists of entry objects (class FilterLogEntry). One for the deleted mails and the other one for the moved mails.
Author:
Ulrich Weigelt <ulrich.weigelt@gmx.de>
Definition at line 52 of file filterlog.h.
Member Enumeration Documentation
anonymous enum [private]
exit - hold log of deleted mails until application exit days - hold log some days
Enumerator:
exit
days
Definition at line 172 of file filterlog.h.
Constructor & Destructor Documentation
FilterLog::FilterLog ()
Default constructor
Definition at line 20 of file filterlog.cpp.
References config, load(), and loadSetup().
FilterLog::~FilterLog ()
Destructor
Definition at line 33 of file filterlog.cpp.
Member Function Documentation
void FilterLog::addDeletedMail (const KDateTime & dateTime, const QString & sender, const QString & account, const QString & subject)
Adds an entry about a deleted mail.
Parameters:
dateTime date and time on which the mail was sent
sender sender of the mail
account Account which has received the mail
subject Subject of the mail
Definition at line 37 of file filterlog.cpp.
References addEntry(), Types::FActDelete, and logDeletedMails.
Referenced by Mail::applyHeaderFilter(), load(), and Mail::writeToDeleteLog().
void FilterLog::addMovedMail (const KDateTime & dateTime, const QString & sender, const QString & account, const QString & subject, const QString & mailbox)
Adds an entry about a moved mail.
Parameters:
dateTime date and time on which the mail was sent
sender sender of the mail
account Account which has received the mail
subject Subject of the mail
mailbox mailbox
Definition at line 43 of file filterlog.cpp.
References addEntry(), Types::FActMove, and logMovedMails.
Referenced by Mail::applyHeaderFilter(), and Mail::writeToMoveLog().
void FilterLog::print ()
Prints the log state.
Definition at line 65 of file filterlog.cpp.
References listDeletedMails, and listMovedMails.
void FilterLog::clearDeletedMailsLog ()
Clears the log of deleted mails.
Definition at line 84 of file filterlog.cpp.
References listDeletedMails.
Referenced by FilterLogView::slotClearDeletedMails().
void FilterLog::clearMovedMailsLog ()
Clears the log of moved mails.
Definition at line 89 of file filterlog.cpp.
References listMovedMails.
Referenced by FilterLogView::slotClearMovedMails().
void FilterLog::save ()
Saved the log of deleted mails as XML document.
Definition at line 94 of file filterlog.cpp.
References daysStoreDeletedMails, deletedMailsStorageMode, exit, listDeletedMails, LOG_DOCTYPE, LOG_FILE, and LOG_ROOT_ELEMENT.
Referenced by KShowmail::queryClose().
void FilterLog::load ()
Loads the log of deleted mails from the XML document and get settings.
Definition at line 138 of file filterlog.cpp.
References addDeletedMail(), daysStoreDeletedMails, LOG_DOCTYPE, LOG_ENTRY_ATTRIBUTE_ACCOUNT, LOG_ENTRY_ATTRIBUTE_DATETIME, LOG_ENTRY_ATTRIBUTE_SENDER, LOG_ENTRY_ATTRIBUTE_SUBJECT, LOG_ENTRY_ELEMENT, LOG_FILE, and LOG_ROOT_ELEMENT.
Referenced by FilterLog().
LogEntryList FilterLog::getDeletedMails ()
Returns a copy of the list of deleted mails.
Returns:
copy of the deleted mails list
Definition at line 191 of file filterlog.cpp.
References listDeletedMails.
Referenced by FilterLogView::FilterLogView().
LogEntryList FilterLog::getMovedMails ()
Retruns a copy of the list of moved mails.
Returns:
copy of the moved mails list
Definition at line 196 of file filterlog.cpp.
References listMovedMails.
Referenced by FilterLogView::FilterLogView().
void FilterLog::loadSetup ()
Loads the settings
Definition at line 201 of file filterlog.cpp.
References config, CONFIG_ENTRY_LOG_HOLDDAYS_DELETED_MAILS, CONFIG_ENTRY_LOG_LOG_DELETED_MAILS, CONFIG_ENTRY_LOG_LOG_MOVED_MAILS, CONFIG_ENTRY_LOG_REMOVE_DELETED_MAILS, CONFIG_GROUP_LOG, CONFIG_VALUE_LOG_REMOVE_MAILS_AFTER_DAYS, CONFIG_VALUE_LOG_REMOVE_MAILS_AT_EXIT, days, daysStoreDeletedMails, DEFAULT_LOG_HOLDDAYS_DELETED_MAILS, DEFAULT_LOG_LOG_DELETED_MAILS, DEFAULT_LOG_LOG_MOVED_MAILS, DEFAULT_LOG_REMOVE_DELETED_MAILS, deletedMailsStorageMode, exit, logDeletedMails, and logMovedMails.
Referenced by FilterLog(), and KShowmail::slotConfChanged().
int FilterLog::numberDeletedMails ()
Returns the number of logged deleted mails.
Returns:
number of logged deleted mails
Definition at line 230 of file filterlog.cpp.
References listDeletedMails.
Referenced by KShowmail::refreshFilterStatusBar().
int FilterLog::numberMovedMails ()
Returns the number of logged moved mails.
Returns:
number of logged moved mails
Definition at line 235 of file filterlog.cpp.
References listMovedMails.
Referenced by KShowmail::refreshFilterStatusBar().
void FilterLog::addEntry (FilterAction_Type action, const KDateTime & dateTime, const QString & sender, const QString & account, const QString & subject, const QString & mailbox = QString()) [protected]
adds an entry. The target list will be coose on the basis of the given filter action.
Definition at line 49 of file filterlog.cpp.
References Types::FActDelete, Types::FActMove, listDeletedMails, listMovedMails, and FilterLogEntry::print().
Referenced by addDeletedMail(), and addMovedMail().
Member Data Documentation
KSharedConfigPtr FilterLog::config [private]
Connector to the configuration file
Definition at line 146 of file filterlog.h.
Referenced by FilterLog(), and loadSetup().
LogEntryList FilterLog::listDeletedMails [private]
List of entries about deleted mails.
Definition at line 151 of file filterlog.h.
Referenced by addEntry(), clearDeletedMailsLog(), getDeletedMails(), numberDeletedMails(), print(), and save().
LogEntryList FilterLog::listMovedMails [private]
List of entries about moved mails.
Definition at line 156 of file filterlog.h.
Referenced by addEntry(), clearMovedMailsLog(), getMovedMails(), numberMovedMails(), and print().
bool FilterLog::logDeletedMails [private]
TRUE - the log accepts orders to log deleted mails
Definition at line 161 of file filterlog.h.
Referenced by addDeletedMail(), and loadSetup().
bool FilterLog::logMovedMails [private]
TRUE - the log accepts orders to log moved mails
Definition at line 166 of file filterlog.h.
Referenced by addMovedMail(), and loadSetup().
enum { ... } FilterLog::deletedMailsStorageMode [private]
exit - hold log of deleted mails until application exit days - hold log some days
Referenced by loadSetup(), and save().
unsigned int FilterLog::daysStoreDeletedMails [private]
Time (days) a entry of a deleted mail will be stored.
Definition at line 177 of file filterlog.h.
Referenced by load(), loadSetup(), and save().
The documentation for this class was generated from the following files:
src/filterlog.h
src/filterlog.cpp