KShowmail: SenderListFilter Class Reference
SenderListFilter Class Reference
This class represents both the blacklist and the whitelist. For using create an object of it and call check() to test a sender address. You have to call load() after the settings in the config file was changed.
#include <senderlistfilter.h>
Public Member Functions
SenderListFilter ()
~SenderListFilter ()
FilterAction_Type check (QString sender) const
void load ()
void print ()
Protected Member Functions
bool search (QStringList list, QString sender) const
Private Attributes
KSharedConfigPtr config
QStringList blacklist
QStringList whitelist
FilterAction_Type blacklistAction
Detailed Description
This class represents both the blacklist and the whitelist. For using create an object of it and call check() to test a sender address. You have to call load() after the settings in the config file was changed.
Author:
Ulrich Weigelt <ulrich.weigelt@gmx.de>
Definition at line 44 of file senderlistfilter.h.
Constructor & Destructor Documentation
SenderListFilter::SenderListFilter ()
Constructor
Definition at line 20 of file senderlistfilter.cpp.
References config, and load().
SenderListFilter::~SenderListFilter ()
Destructor
Definition at line 32 of file senderlistfilter.cpp.
Member Function Documentation
FilterAction_Type SenderListFilter::check (QString sender) const
Checks the given sender whether it is listed in the blacklist or whitelist.
Parameters:
sender sender which shall be checked
Returns:
appointed action (FActPass, FActDelete, FActMark, FActNone)
Definition at line 36 of file senderlistfilter.cpp.
References blacklist, blacklistAction, Types::FActNone, Types::FActPass, search(), and whitelist.
Referenced by HeaderFilter::check().
void SenderListFilter::load ()
Loads the setup from the application config file.
Definition at line 51 of file senderlistfilter.cpp.
References blacklist, blacklistAction, config, CONFIG_ENTRY_FILTER_BLACKLIST, CONFIG_ENTRY_FILTER_BLACKLIST_ACTION, CONFIG_ENTRY_FILTER_WHITELIST, CONFIG_GROUP_FILTER, CONFIG_VALUE_FILTER_BLACKLIST_ACTION_DELETE, CONFIG_VALUE_FILTER_BLACKLIST_ACTION_MARK, DEFAULT_FILTER_BLACKLIST_ACTION, Types::FActDelete, Types::FActMark, and whitelist.
Referenced by HeaderFilter::load(), and SenderListFilter().
void SenderListFilter::print ()
Prints the settings.
Definition at line 85 of file senderlistfilter.cpp.
References blacklist, blacklistAction, Types::FActDelete, Types::FActMark, and whitelist.
Referenced by HeaderFilter::print().
bool SenderListFilter::search (QStringList list, QString sender) const [protected]
Returns TRUE if the given list contains the sender or a part of it. e.g.: The list contains: Ulrich Weigelt spam@spamhouse.com "Lara Croft" <lara.croft@tombraider.com>
This sender strings will cause a return value of TRUE: "Ulrich Weigelt" <ulrich.weigelt@gmx.de> "Spam King" <spam@spamhouse.com> spam@spamhouse.com lara.croft@tombraider.com "Lara Croft" <lara.croft@tombraider.com>
Parameters:
list blacklist or whitelist
sender searched sender name
Returns:
TRUE - the given sender name is listed. FALSE - is not listed
Definition at line 69 of file senderlistfilter.cpp.
Referenced by check().
Member Data Documentation
KSharedConfigPtr SenderListFilter::config [private]
Connector to the configuration file
Definition at line 80 of file senderlistfilter.h.
Referenced by load(), and SenderListFilter().
QStringList SenderListFilter::blacklist [private]
blacklisted addresses
Definition at line 85 of file senderlistfilter.h.
Referenced by check(), load(), and print().
QStringList SenderListFilter::whitelist [private]
whitelisted addresses
Definition at line 90 of file senderlistfilter.h.
Referenced by check(), load(), and print().
FilterAction_Type SenderListFilter::blacklistAction [private]
appointed action of the blacklist.
Definition at line 95 of file senderlistfilter.h.
Referenced by check(), load(), and print().
The documentation for this class was generated from the following files:
src/senderlistfilter.h
src/senderlistfilter.cpp