KShowmail: FilterSetupDialog Class Reference
FilterSetupDialog Class Reference
Dialog to setup a filter.
#include <filtersetupdialog.h>
Public Member Functions
FilterSetupDialog (QWidget *parent, FilterSetupItem *item=NULL)
~FilterSetupDialog ()
Protected Slots
void slotButtonClicked (int button)
void slotActionChanged (int index)
FilterCriteriaWidget * slotAddCriteriaWidget ()
void slotRemoveCriteriaWidget ()
void slotOpenMailBoxWizard ()
Protected Member Functions
void fillDialog ()
void addCriteriaWidget (int source, int condition, uint value)
void addCriteriaWidget (int source, int condition, QString value, bool cs)
Private Attributes
FilterSetupItem * filter
QTreeWidget * listView
KLineEdit * txtName
QButtonGroup * grpLinkage
QWidget * wdgCriteriasHolding
QVBoxLayout * layCriteriasHolding
KPushButton * btnAddCriteria
KPushButton * btnRemoveCriteria
KComboBox * cmbAction
KLineEdit * txtMailbox
KPushButton * btnMailboxWizard
Detailed Description
Dialog to setup a filter.
Author:
Ulrich Weigelt <ulrich.weigelt@gmx.de>
Definition at line 59 of file filtersetupdialog.h.
Constructor & Destructor Documentation
FilterSetupDialog::FilterSetupDialog (QWidget * parent, FilterSetupItem * item = NULL) [explicit]
General constructor
Parameters:
parent parent of the dialog
item filter to setup;
Definition at line 20 of file filtersetupdialog.cpp.
References btnAddCriteria, btnMailboxWizard, btnRemoveCriteria, cmbAction, CONFIG_VALUE_FILTER_ACTION_DELETE, CONFIG_VALUE_FILTER_ACTION_IGNORE, CONFIG_VALUE_FILTER_ACTION_MARK, CONFIG_VALUE_FILTER_ACTION_MOVE, CONFIG_VALUE_FILTER_ACTION_PASS, CONFIG_VALUE_FILTER_ACTION_SPAMCHECK, CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ALL, CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ANY, DEFAULT_FILTER_ACTION, DEFAULT_FILTER_CRITERIA_LINKAGE, DEFAULT_FILTER_NAME, fillDialog(), filter, FilterSetupItem::getName(), grpLinkage, ID_BUTTON_LINKAGE_MATCH_ALL, ID_BUTTON_LINKAGE_MATCH_ANY, ID_COMBO_FILTER_ACTION_DELETE, ID_COMBO_FILTER_ACTION_IGNORE, ID_COMBO_FILTER_ACTION_MARK, ID_COMBO_FILTER_ACTION_MOVE, ID_COMBO_FILTER_ACTION_PASS, ID_COMBO_FILTER_ACTION_SPAMCHECK, layCriteriasHolding, slotActionChanged(), slotAddCriteriaWidget(), slotOpenMailBoxWizard(), slotRemoveCriteriaWidget(), txtMailbox, txtName, and wdgCriteriasHolding.
FilterSetupDialog::~FilterSetupDialog ()
Destructor
Definition at line 147 of file filtersetupdialog.cpp.
Member Function Documentation
void FilterSetupDialog::fillDialog () [protected]
Writes the values of the given filter into the dialog items.
Definition at line 151 of file filtersetupdialog.cpp.
References addCriteriaWidget(), cmbAction, CONFIG_VALUE_FILTER_ACTION_DELETE, CONFIG_VALUE_FILTER_ACTION_IGNORE, CONFIG_VALUE_FILTER_ACTION_MARK, CONFIG_VALUE_FILTER_ACTION_MOVE, CONFIG_VALUE_FILTER_ACTION_PASS, CONFIG_VALUE_FILTER_ACTION_SPAMCHECK, CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ALL, CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ANY, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_ACCOUNT, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_FROM, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_HEADER, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_SIZE, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_SUBJECT, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_TO, DEFAULT_FILTER_ACTION, DEFAULT_FILTER_CRITERIA_LINKAGE, filter, FilterSetupItem::getAction(), FilterSetupItem::getCriteriaLinkage(), FilterSetupItem::getCriteriaList(), FilterSetupItem::getMailBox(), FilterSetupItem::getName(), grpLinkage, ID_BUTTON_LINKAGE_MATCH_ALL, ID_BUTTON_LINKAGE_MATCH_ANY, ID_COMBO_FILTER_ACTION_DELETE, ID_COMBO_FILTER_ACTION_IGNORE, ID_COMBO_FILTER_ACTION_MARK, ID_COMBO_FILTER_ACTION_MOVE, ID_COMBO_FILTER_ACTION_PASS, ID_COMBO_FILTER_ACTION_SPAMCHECK, slotActionChanged(), slotAddCriteriaWidget(), txtMailbox, and txtName.
Referenced by FilterSetupDialog().
void FilterSetupDialog::addCriteriaWidget (int source, int condition, uint value) [protected]
Adds a criteria widget dialog with values for numeric comparison.
Parameters:
source Object of Comparison. It accepts only numeric objects (e.g. Size) (see constants.h for valid values)
condition Condition of the comparison (see constants.h for valid values)
value comparison value
Definition at line 310 of file filtersetupdialog.cpp.
References CONFIG_VALUE_FILTER_CRITERIA_COND_NUM_EQUAL, CONFIG_VALUE_FILTER_CRITERIA_COND_NUM_GREATER, CONFIG_VALUE_FILTER_CRITERIA_COND_NUM_GREATER_EQUAL, CONFIG_VALUE_FILTER_CRITERIA_COND_NUM_LESS, CONFIG_VALUE_FILTER_CRITERIA_COND_NUM_LESS_EQUAL, CONFIG_VALUE_FILTER_CRITERIA_COND_NUM_NOT_EQUAL, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_SIZE, FilterCriteriaWidget::setNumCriteria(), and slotAddCriteriaWidget().
Referenced by fillDialog().
void FilterSetupDialog::addCriteriaWidget (int source, int condition, QString value, bool cs) [protected]
Adds a criteria widget dialog with values for text comparison.
Parameters:
source Object of Comparison. It accepts only text objects (e.g. Subject) (see constants.h for valid values)
condition Condition of the comparison (see constants.h for valid values)
value comparison string
cs TRUE - comparison is case sensitive; FALSE - comparison is not case sensitive
Definition at line 337 of file filtersetupdialog.cpp.
References CONFIG_VALUE_FILTER_CRITERIA_COND_TEXT_CONTAINS, CONFIG_VALUE_FILTER_CRITERIA_COND_TEXT_EQUALS, CONFIG_VALUE_FILTER_CRITERIA_COND_TEXT_NOT_CONTAINS, CONFIG_VALUE_FILTER_CRITERIA_COND_TEXT_NOT_EQUALS, CONFIG_VALUE_FILTER_CRITERIA_COND_TEXT_NOT_REGEXPR, CONFIG_VALUE_FILTER_CRITERIA_COND_TEXT_REGEXPR, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_ACCOUNT, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_FROM, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_HEADER, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_SUBJECT, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_TO, FilterCriteriaWidget::setTextCriteria(), FilterCriteriaWidget::setTextListCriteria(), and slotAddCriteriaWidget().
void FilterSetupDialog::slotButtonClicked (int button) [protected, slot]
Overwritten method of KDialog. Called if a button is clocked clicked. Stores the entered values into the given account item. If no item was given it creates a new one. After then it invokes slotButtonClicked() of KDialog.
Parameters:
button clicked button
Definition at line 376 of file filtersetupdialog.cpp.
References cmbAction, CONFIG_VALUE_FILTER_ACTION_DELETE, CONFIG_VALUE_FILTER_ACTION_IGNORE, CONFIG_VALUE_FILTER_ACTION_MARK, CONFIG_VALUE_FILTER_ACTION_MOVE, CONFIG_VALUE_FILTER_ACTION_PASS, CONFIG_VALUE_FILTER_ACTION_SPAMCHECK, CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ALL, CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ANY, DEFAULT_FILTER_ACTION, DEFAULT_FILTER_CRITERIA_LINKAGE, filter, FILTER_CRITERIA_WIDGET_NAME, grpLinkage, ID_BUTTON_LINKAGE_MATCH_ALL, ID_BUTTON_LINKAGE_MATCH_ANY, ID_COMBO_FILTER_ACTION_DELETE, ID_COMBO_FILTER_ACTION_IGNORE, ID_COMBO_FILTER_ACTION_MARK, ID_COMBO_FILTER_ACTION_MOVE, ID_COMBO_FILTER_ACTION_PASS, ID_COMBO_FILTER_ACTION_SPAMCHECK, FilterSetupItem::setAction(), FilterSetupItem::setCriteriaLinkage(), FilterSetupItem::setCriteriaList(), FilterSetupItem::setMailBox(), FilterSetupItem::setName(), txtMailbox, txtName, and wdgCriteriasHolding.
void FilterSetupDialog::slotActionChanged (int index) [protected, slot]
Connected with combobox cmbAction. Enables or disables additional widgets for action configuration.
Parameters:
index position (index) of the selected action
Definition at line 451 of file filtersetupdialog.cpp.
References btnMailboxWizard, DEFAULT_FILTER_ACTION_MOVE_MAILBOX, ID_COMBO_FILTER_ACTION_MOVE, and txtMailbox.
Referenced by fillDialog(), and FilterSetupDialog().
FilterCriteriaWidget * FilterSetupDialog::slotAddCriteriaWidget () [protected, slot]
Adds a empty critera dialog widget.
Returns:
Pointer to the new widget
Definition at line 250 of file filtersetupdialog.cpp.
References btnRemoveCriteria, layCriteriasHolding, and wdgCriteriasHolding.
Referenced by addCriteriaWidget(), fillDialog(), and FilterSetupDialog().
void FilterSetupDialog::slotRemoveCriteriaWidget () [protected, slot]
Removes the last criteria dialog widget.
Definition at line 272 of file filtersetupdialog.cpp.
References btnRemoveCriteria, FILTER_CRITERIA_WIDGET_NAME, layCriteriasHolding, and wdgCriteriasHolding.
Referenced by FilterSetupDialog().
void FilterSetupDialog::slotOpenMailBoxWizard () [protected, slot]
Connected with button btnMailboxWizard. Opens a wizard to configure the mailbox
Definition at line 465 of file filtersetupdialog.cpp.
References txtMailbox.
Referenced by FilterSetupDialog().
Member Data Documentation
FilterSetupItem* FilterSetupDialog::filter [private]
filter to setup
Definition at line 82 of file filtersetupdialog.h.
Referenced by fillDialog(), FilterSetupDialog(), and slotButtonClicked().
QTreeWidget* FilterSetupDialog::listView [private]
View which shows the filter items.
Definition at line 87 of file filtersetupdialog.h.
KLineEdit* FilterSetupDialog::txtName [private]
Contains the filter name.
Definition at line 92 of file filtersetupdialog.h.
Referenced by fillDialog(), FilterSetupDialog(), and slotButtonClicked().
QButtonGroup* FilterSetupDialog::grpLinkage [private]
Combines the radio buttons to select the kind of linkage between the criterias.
Definition at line 97 of file filtersetupdialog.h.
Referenced by fillDialog(), FilterSetupDialog(), and slotButtonClicked().
QWidget* FilterSetupDialog::wdgCriteriasHolding [private]
This widget holds one ore more filter criteria dialogs (class FilterCriteriaWidget).
Definition at line 102 of file filtersetupdialog.h.
Referenced by FilterSetupDialog(), slotAddCriteriaWidget(), slotButtonClicked(), and slotRemoveCriteriaWidget().
QVBoxLayout* FilterSetupDialog::layCriteriasHolding [private]
Layout for wdgCriterias.
Definition at line 107 of file filtersetupdialog.h.
Referenced by FilterSetupDialog(), slotAddCriteriaWidget(), and slotRemoveCriteriaWidget().
KPushButton* FilterSetupDialog::btnAddCriteria [private]
Button to add a criteria dialog.
Definition at line 112 of file filtersetupdialog.h.
Referenced by FilterSetupDialog().
KPushButton* FilterSetupDialog::btnRemoveCriteria [private]
Button to remove the last criteria.
Definition at line 117 of file filtersetupdialog.h.
Referenced by FilterSetupDialog(), slotAddCriteriaWidget(), and slotRemoveCriteriaWidget().
KComboBox* FilterSetupDialog::cmbAction [private]
Combobox to select the action.
Definition at line 122 of file filtersetupdialog.h.
Referenced by fillDialog(), FilterSetupDialog(), and slotButtonClicked().
KLineEdit* FilterSetupDialog::txtMailbox [private]
If selected, the mails will be moved to the mailbox which is written in this edit line.
Definition at line 127 of file filtersetupdialog.h.
Referenced by fillDialog(), FilterSetupDialog(), slotActionChanged(), slotButtonClicked(), and slotOpenMailBoxWizard().
KPushButton* FilterSetupDialog::btnMailboxWizard [private]
This button opens a wizard which will help to get the right mailbox
Definition at line 132 of file filtersetupdialog.h.
Referenced by FilterSetupDialog(), and slotActionChanged().
The documentation for this class was generated from the following files:
src/filtersetupdialog.h
src/filtersetupdialog.cpp