KShowmail: FilterLogView Class Reference
FilterLogView Class Reference
This dialog box shows the filter log.
#include <filterlogview.h>
Public Member Functions
FilterLogView (QWidget *parent=NULL, FilterLog *log=NULL)
~FilterLogView ()
Private Slots
void slotClearDeletedMails ()
void slotClearMovedMails ()
virtual void slotButtonClicked (int button)
Private Attributes
FilterLog * log
QTreeWidget * lstViewDeleted
QTreeWidget * lstViewMoved
KSharedConfigPtr config
Detailed Description
This dialog box shows the filter log.
Author:
Ulrich Weigelt <ulrich.weigelt@gmx.de>
Definition at line 49 of file filterlogview.h.
Constructor & Destructor Documentation
FilterLogView::FilterLogView (QWidget * parent = NULL, FilterLog * log = NULL) [explicit]
General constructor
Parameters:
parent pointer to the parent widget
log pointer to the filter log
Definition at line 20 of file filterlogview.cpp.
References config, CONFIG_GROUP, FilterLog::getDeletedMails(), FilterLog::getMovedMails(), lstViewDeleted, lstViewMoved, FilterLogViewMovedItem::setValues(), FilterLogViewDeletedItem::setValues(), slotClearDeletedMails(), and slotClearMovedMails().
FilterLogView::~FilterLogView ()
Destructor
Definition at line 117 of file filterlogview.cpp.
Member Function Documentation
void FilterLogView::slotClearDeletedMails () [private, slot]
Clears the list of deleted mails.
Definition at line 121 of file filterlogview.cpp.
References FilterLog::clearDeletedMailsLog(), log, and lstViewDeleted.
Referenced by FilterLogView().
void FilterLogView::slotClearMovedMails () [private, slot]
Clears th elist of moved mails.
Definition at line 128 of file filterlogview.cpp.
References FilterLog::clearMovedMailsLog(), log, and lstViewMoved.
Referenced by FilterLogView().
void FilterLogView::slotButtonClicked (int button) [private, virtual, slot]
Overloaded from KDialog.
Activated when the button button is clicked.
Parameters:
button clocked button
Definition at line 134 of file filterlogview.cpp.
References config, and CONFIG_GROUP.
Member Data Documentation
FilterLog* FilterLogView::log [private]
Pointer to the filter log.
Definition at line 73 of file filterlogview.h.
Referenced by slotClearDeletedMails(), and slotClearMovedMails().
QTreeWidget* FilterLogView::lstViewDeleted [private]
List view of deleted mails
Definition at line 78 of file filterlogview.h.
Referenced by FilterLogView(), and slotClearDeletedMails().
QTreeWidget* FilterLogView::lstViewMoved [private]
List view of moved mails
Definition at line 83 of file filterlogview.h.
Referenced by FilterLogView(), and slotClearMovedMails().
KSharedConfigPtr FilterLogView::config [private]
Connector to the configuration file
Definition at line 88 of file filterlogview.h.
Referenced by FilterLogView(), and slotButtonClicked().
The documentation for this class was generated from the following files:
src/filterlogview.h
src/filterlogview.cpp