KShowmail: AccountSetupItem Class Reference
AccountSetupItem Class Reference
This class is used in ConfigAccounts to show the available accounts in the list view and to store an account setup.
#include <accountsetupitem.h>
Public Member Functions
AccountSetupItem (QTreeWidget *parent)
Constructor.
AccountSetupItem (QTreeWidget *parent, const QString &name)
Constructor.
~AccountSetupItem ()
Destructor.
void setAccountName (const QString &name)
Sets account name.
QString getAccountName () const
Returns the account name.
void setServer (const QString &server)
Sets the server.
QString getServer () const
Returns the server.
void setProtocol (const QString &protocol)
Sets the protocol.
QString getProtocol () const
Returns the protocol.
void setPort (int port)
Sets the port number.
int getPort () const
Returns the port number.
void setUser (const QString &user)
Sets the user name.
QString getUser () const
Returns the user name.
void setPassword (const QString &password)
Sets the password.
QString getPassword () const
Returns the password.
void setPasswordStorageType (int type)
Sets the password storage type.
int getPasswordStorageType () const
Returns the password storage type.
void setActive (bool active)
Sets whether the account is active.
bool getActive () const
Returns whether the account is active.
void setTransferSecurity (int type)
Sets the transfer security.
int getTransferSecurity () const
Returns the transfer security.
void save () const
Saves this account into applications config.
void load ()
Loads the options of this account from the application config.
void print ()
Prints the account settings to stdout.
void setUnsecureLoginAllowed (bool allowed)
Sets whether an unsecure login is allowed.
bool getUnsecureLoginAllowed () const
Return whether an unsecure login is allowed.
Protected Member Functions
void init ()
Initializes the object.
Private Attributes
KSharedConfigPtr config
Connector to the configuration file.
QString _account
Account name.
QString _server
Server.
QString _protocol
Protocol.
int _port
Port.
QString _user
User Name.
QString _password
Password.
bool _active
TRUE - account is active.
int _passwordStorage
password storage type
int _transferSecurity
transfer security
bool _allowUnsecureLogin
TRUE - unsafe login is allowed if a secure login failed.
Detailed Description
This class is used in ConfigAccounts to show the available accounts in the list view and to store an account setup.
Author:
Ulrich Weigelt <ulrich.weigelt@gmx.de>
Definition at line 43 of file accountsetupitem.h.
Constructor & Destructor Documentation
AccountSetupItem::AccountSetupItem (QTreeWidget * parent)
Constructor.
Parameters:
parent the list view
Definition at line 20 of file accountsetupitem.cpp.
References init().
AccountSetupItem::AccountSetupItem (QTreeWidget * parent, const QString & name)
Constructor.
Parameters:
parent the list view
name account name
Definition at line 27 of file accountsetupitem.cpp.
References _account, and init().
AccountSetupItem::~AccountSetupItem ()
Destructor.
Definition at line 40 of file accountsetupitem.cpp.
Member Function Documentation
void AccountSetupItem::setAccountName (const QString & name)
Sets account name.
Parameters:
name account name
Definition at line 65 of file accountsetupitem.cpp.
References _account.
Referenced by AccountSetupDialog::slotButtonClicked().
QString AccountSetupItem::getAccountName () const
Returns the account name.
Returns:
account name
Definition at line 70 of file accountsetupitem.cpp.
References _account.
Referenced by AccountSetupDialog::fillDialog(), load(), print(), ConfigAccounts::save(), save(), AccountSetupDialog::slotButtonClicked(), and ConfigAccounts::slotRemove().
void AccountSetupItem::setServer (const QString & server)
Sets the server.
Parameters:
server server
Definition at line 75 of file accountsetupitem.cpp.
References _server.
Referenced by AccountSetupDialog::slotButtonClicked().
QString AccountSetupItem::getServer () const
Returns the server.
Returns:
server
Definition at line 80 of file accountsetupitem.cpp.
References _server.
Referenced by AccountSetupDialog::fillDialog(), print(), and save().
void AccountSetupItem::setProtocol (const QString & protocol)
Sets the protocol.
Parameters:
protocol protocol
Definition at line 85 of file accountsetupitem.cpp.
References _protocol.
Referenced by AccountSetupDialog::slotButtonClicked().
QString AccountSetupItem::getProtocol () const
Returns the protocol.
Returns:
protocol
Definition at line 90 of file accountsetupitem.cpp.
References _protocol.
Referenced by AccountSetupDialog::fillDialog(), print(), and save().
void AccountSetupItem::setPort (int port)
Sets the port number.
Parameters:
port port number
Definition at line 95 of file accountsetupitem.cpp.
References _port, and DEFAULT_ACCOUNT_PORT_POP3.
Referenced by AccountSetupDialog::slotButtonClicked().
int AccountSetupItem::getPort () const
Returns the port number.
Returns:
port number (0..65535)
Definition at line 103 of file accountsetupitem.cpp.
References _port.
Referenced by AccountSetupDialog::fillDialog(), print(), and save().
void AccountSetupItem::setUser (const QString & user)
Sets the user name.
Parameters:
user user name
Definition at line 108 of file accountsetupitem.cpp.
References _user.
Referenced by AccountSetupDialog::slotButtonClicked().
QString AccountSetupItem::getUser () const
Returns the user name.
Returns:
user name
Definition at line 113 of file accountsetupitem.cpp.
References _user.
Referenced by AccountSetupDialog::fillDialog(), print(), and save().
void AccountSetupItem::setPassword (const QString & password)
Sets the password.
Parameters:
password password
Definition at line 118 of file accountsetupitem.cpp.
References _password.
Referenced by AccountSetupDialog::slotButtonClicked().
QString AccountSetupItem::getPassword () const
Returns the password.
Returns:
password
Definition at line 123 of file accountsetupitem.cpp.
References _password.
Referenced by AccountSetupDialog::fillDialog(), print(), and save().
void AccountSetupItem::setPasswordStorageType (int type)
Sets the password storage type.
See constants.h for valid values
Parameters:
type password storage type (CONFIG_VALUE_ACCOUNT_PASSWORD_DONT_SAVE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_FILE or CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_KWALLET)
Definition at line 128 of file accountsetupitem.cpp.
References _passwordStorage, CONFIG_VALUE_ACCOUNT_PASSWORD_DONT_SAVE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_FILE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_KWALLET, and DEFAULT_ACCOUNT_PASSWORD_STORAGE.
Referenced by AccountSetupDialog::slotButtonClicked().
int AccountSetupItem::getPasswordStorageType () const
Returns the password storage type.
See constants.h for valid values (CONFIG_VALUE_ACCOUNT_PASSWORD_...)
Returns:
storage type
Definition at line 136 of file accountsetupitem.cpp.
References _passwordStorage.
Referenced by AccountSetupDialog::fillDialog(), print(), and save().
void AccountSetupItem::setActive (bool active)
Sets whether the account is active.
Parameters:
active TRUE - account is active; FALSE - account is not active
Definition at line 141 of file accountsetupitem.cpp.
References _active.
Referenced by AccountSetupDialog::slotButtonClicked().
bool AccountSetupItem::getActive () const
Returns whether the account is active.
Returns:
TRUE - account is active
FALSE - account is not active
Definition at line 146 of file accountsetupitem.cpp.
References _active.
Referenced by AccountSetupDialog::fillDialog(), print(), and save().
void AccountSetupItem::setTransferSecurity (int type)
Sets the transfer security.
See constants.h for valid values.
Parameters:
type transfer security type (CONFIG_VALUE_ACCOUNT_SECTRANSFER_NONE, CONFIG_VALUE_ACCOUNT_SECTRANSFER_SSL, CONFIG_VALUE_ACCOUNT_SECTRANSFER_TLS)
Definition at line 205 of file accountsetupitem.cpp.
References _transferSecurity, CONFIG_VALUE_ACCOUNT_SECTRANSFER_NONE, CONFIG_VALUE_ACCOUNT_SECTRANSFER_SSL, CONFIG_VALUE_ACCOUNT_SECTRANSFER_TLS, and DEFAULT_ACCOUNT_SECTRANSFER.
Referenced by AccountSetupDialog::slotButtonClicked().
int AccountSetupItem::getTransferSecurity () const
Returns the transfer security.
seee constants.h for valid values (CONFIG_VALUE_ACCOUNT_SECTRANSFER_...)
Returns:
transfer security
Definition at line 213 of file accountsetupitem.cpp.
References _transferSecurity.
Referenced by AccountSetupDialog::fillDialog(), print(), and save().
void AccountSetupItem::save () const
Saves this account into applications config.
All values are placed in a group called like the account name.
Definition at line 151 of file accountsetupitem.cpp.
References config, CONFIG_ENTRY_ACCOUNT_ACTIVE, CONFIG_ENTRY_ACCOUNT_ALLOW_UNSECURE_LOGIN, CONFIG_ENTRY_ACCOUNT_NAME, CONFIG_ENTRY_ACCOUNT_PASSWORD, CONFIG_ENTRY_ACCOUNT_PASSWORD_STORAGE, CONFIG_ENTRY_ACCOUNT_PORT, CONFIG_ENTRY_ACCOUNT_PROTOCOL, CONFIG_ENTRY_ACCOUNT_SECTRANSFER, CONFIG_ENTRY_ACCOUNT_SERVER, CONFIG_ENTRY_ACCOUNT_USER, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_FILE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_KWALLET, Encryption::crypt(), getAccountName(), getActive(), getPassword(), getPasswordStorageType(), getPort(), getProtocol(), getServer(), getTransferSecurity(), getUnsecureLoginAllowed(), getUser(), and KWalletAccess::savePassword().
Referenced by ConfigAccounts::save().
void AccountSetupItem::load ()
Loads the options of this account from the application config.
Definition at line 183 of file accountsetupitem.cpp.
References _active, _allowUnsecureLogin, _password, _passwordStorage, _port, _protocol, _server, _transferSecurity, _user, config, CONFIG_ENTRY_ACCOUNT_ACTIVE, CONFIG_ENTRY_ACCOUNT_ALLOW_UNSECURE_LOGIN, CONFIG_ENTRY_ACCOUNT_PASSWORD, CONFIG_ENTRY_ACCOUNT_PASSWORD_STORAGE, CONFIG_ENTRY_ACCOUNT_PORT, CONFIG_ENTRY_ACCOUNT_PROTOCOL, CONFIG_ENTRY_ACCOUNT_SECTRANSFER, CONFIG_ENTRY_ACCOUNT_SERVER, CONFIG_ENTRY_ACCOUNT_USER, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_FILE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_KWALLET, Encryption::decrypt(), DEFAULT_ACCOUNT_ACTIVE, DEFAULT_ACCOUNT_ALLOW_UNSECURE_LOGIN, DEFAULT_ACCOUNT_PASSWORD, DEFAULT_ACCOUNT_PASSWORD_STORAGE, DEFAULT_ACCOUNT_PORT_POP3, DEFAULT_ACCOUNT_PROTOCOL, DEFAULT_ACCOUNT_SECTRANSFER, DEFAULT_ACCOUNT_SERVER, DEFAULT_ACCOUNT_USER, getAccountName(), and KWalletAccess::getPassword().
Referenced by ConfigAccounts::load().
void AccountSetupItem::print ()
Prints the account settings to stdout.
Definition at line 218 of file accountsetupitem.cpp.
References CONFIG_VALUE_ACCOUNT_PASSWORD_DONT_SAVE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_FILE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_KWALLET, CONFIG_VALUE_ACCOUNT_SECTRANSFER_NONE, CONFIG_VALUE_ACCOUNT_SECTRANSFER_SSL, CONFIG_VALUE_ACCOUNT_SECTRANSFER_TLS, getAccountName(), getActive(), getPassword(), getPasswordStorageType(), getPort(), getProtocol(), getServer(), getTransferSecurity(), and getUser().
void AccountSetupItem::setUnsecureLoginAllowed (bool allowed)
Sets whether an unsecure login is allowed.
Parameters:
allowed TRUE - unsecure login is allowd
Definition at line 261 of file accountsetupitem.cpp.
References _allowUnsecureLogin.
Referenced by AccountSetupDialog::slotButtonClicked().
bool AccountSetupItem::getUnsecureLoginAllowed () const
Return whether an unsecure login is allowed.
Returns:
TRUE - unsecure login is allowed
Definition at line 266 of file accountsetupitem.cpp.
References _allowUnsecureLogin.
Referenced by AccountSetupDialog::fillDialog(), and save().
void AccountSetupItem::init () [protected]
Initializes the object.
Definition at line 44 of file accountsetupitem.cpp.
References _account, _active, _password, _passwordStorage, _port, _protocol, _server, _transferSecurity, _user, config, DEFAULT_ACCOUNT_ACTIVE, DEFAULT_ACCOUNT_NAME, DEFAULT_ACCOUNT_PASSWORD, DEFAULT_ACCOUNT_PASSWORD_STORAGE, DEFAULT_ACCOUNT_PORT_POP3, DEFAULT_ACCOUNT_PROTOCOL, DEFAULT_ACCOUNT_SECTRANSFER, DEFAULT_ACCOUNT_SERVER, and DEFAULT_ACCOUNT_USER.
Referenced by AccountSetupItem().
Member Data Documentation
KSharedConfigPtr AccountSetupItem::config [private]
Connector to the configuration file.
Definition at line 218 of file accountsetupitem.h.
Referenced by init(), load(), and save().
QString AccountSetupItem::_account [private]
Account name.
Definition at line 223 of file accountsetupitem.h.
Referenced by AccountSetupItem(), getAccountName(), init(), and setAccountName().
QString AccountSetupItem::_server [private]
Server.
Definition at line 228 of file accountsetupitem.h.
Referenced by getServer(), init(), load(), and setServer().
QString AccountSetupItem::_protocol [private]
Protocol.
Definition at line 233 of file accountsetupitem.h.
Referenced by getProtocol(), init(), load(), and setProtocol().
int AccountSetupItem::_port [private]
Port.
Definition at line 238 of file accountsetupitem.h.
Referenced by getPort(), init(), load(), and setPort().
QString AccountSetupItem::_user [private]
User Name.
Definition at line 243 of file accountsetupitem.h.
Referenced by getUser(), init(), load(), and setUser().
QString AccountSetupItem::_password [private]
Password.
Definition at line 248 of file accountsetupitem.h.
Referenced by getPassword(), init(), load(), and setPassword().
bool AccountSetupItem::_active [private]
TRUE - account is active.
Definition at line 253 of file accountsetupitem.h.
Referenced by getActive(), init(), load(), and setActive().
int AccountSetupItem::_passwordStorage [private]
password storage type
Values are defined in constants.h (CONFIG_VALUE_ACCOUNT_PASSWORD_...)
Definition at line 260 of file accountsetupitem.h.
Referenced by getPasswordStorageType(), init(), load(), and setPasswordStorageType().
int AccountSetupItem::_transferSecurity [private]
transfer security
Values are defined in constants.h (CONFIG_VALUE_ACCOUNT_SECTRANSFER_...)
Definition at line 267 of file accountsetupitem.h.
Referenced by getTransferSecurity(), init(), load(), and setTransferSecurity().
bool AccountSetupItem::_allowUnsecureLogin [private]
TRUE - unsafe login is allowed if a secure login failed.
Definition at line 272 of file accountsetupitem.h.
Referenced by getUnsecureLoginAllowed(), load(), and setUnsecureLoginAllowed().
The documentation for this class was generated from the following files:
src/accountsetupitem.h
src/accountsetupitem.cpp