KShowmail: ConfigSpamcheck Class Reference
ConfigSpamcheck Class Reference
Part of the setup dialog (KShowMailApp::SetupDialog) to configure the spam check.
#include <configspamcheck.h>
Public Member Functions
ConfigSpamcheck (QWidget *parent=0, const QVariantList &args=QVariantList())
~ConfigSpamcheck ()
virtual void load ()
virtual void defaults ()
virtual void save ()
Protected Member Functions
bool isSpamAssassinRunning () const
Private Slots
void slotChanged ()
void slotActionChanged (int index)
void slotOpenMailBoxWizard ()
void slotTestSpamAssassin ()
Private Attributes
KSharedConfigPtr config
KPushButton * btnTest
KComboBox * cmbAction
KLineEdit * txtMailbox
KPushButton * btnMailboxWizard
QGroupBox * gboxAction
Detailed Description
Part of the setup dialog (KShowMailApp::SetupDialog) to configure the spam check.
Author:
Ulrich Weigelt <ulrich.weigelt@gmx.de>
Definition at line 60 of file configspamcheck.h.
Constructor & Destructor Documentation
ConfigSpamcheck::ConfigSpamcheck (QWidget * parent = 0, const QVariantList & args = QVariantList()) [explicit]
Generic constructor
ConfigSpamcheck::~ConfigSpamcheck ()
Destructor
Definition at line 95 of file configspamcheck.cpp.
Member Function Documentation
void ConfigSpamcheck::load () [virtual]
Overloaded method of KCModule. Sets the user interface elements to reflect the current settings stored in the config file.
Definition at line 99 of file configspamcheck.cpp.
References cmbAction, config, CONFIG_ENTRY_SPAMCHECK_ACTION, CONFIG_ENTRY_SPAMCHECK_MOVE_MAILBOX, CONFIG_GROUP_SPAMCHECK, CONFIG_VALUE_SPAMCHECK_ACTION_DELETE, CONFIG_VALUE_SPAMCHECK_ACTION_MARK, CONFIG_VALUE_SPAMCHECK_ACTION_MOVE, DEFAULT_SPAMCHECK_ACTION, DEFAULT_SPAMCHECK_ACTION_MOVE_MAILBOX, ID_SPAM_ACTION_BUTTONS_DELETE, ID_SPAM_ACTION_BUTTONS_MARK, ID_SPAM_ACTION_BUTTONS_MOVE, slotActionChanged(), and txtMailbox.
void ConfigSpamcheck::defaults () [virtual]
Overloaded method of KCModule. Sets the user interface elements to default values. This method is called when the user clicks the "Default" button.
Definition at line 121 of file configspamcheck.cpp.
References cmbAction, CONFIG_VALUE_SPAMCHECK_ACTION_DELETE, CONFIG_VALUE_SPAMCHECK_ACTION_MARK, CONFIG_VALUE_SPAMCHECK_ACTION_MOVE, DEFAULT_SPAMCHECK_ACTION, DEFAULT_SPAMCHECK_ACTION_MOVE_MAILBOX, ID_SPAM_ACTION_BUTTONS_DELETE, ID_SPAM_ACTION_BUTTONS_MARK, ID_SPAM_ACTION_BUTTONS_MOVE, slotActionChanged(), slotChanged(), and txtMailbox.
void ConfigSpamcheck::save () [virtual]
Overloaded method of KCModule. Stores the config information as shown in the user interface in the config file. Is called when the user clicks "Apply" or "Ok".
Definition at line 141 of file configspamcheck.cpp.
References cmbAction, config, CONFIG_ENTRY_SPAMCHECK_ACTION, CONFIG_ENTRY_SPAMCHECK_MOVE_MAILBOX, CONFIG_GROUP_SPAMCHECK, CONFIG_VALUE_SPAMCHECK_ACTION_DELETE, CONFIG_VALUE_SPAMCHECK_ACTION_MARK, CONFIG_VALUE_SPAMCHECK_ACTION_MOVE, DEFAULT_SPAMCHECK_ACTION, ID_SPAM_ACTION_BUTTONS_DELETE, ID_SPAM_ACTION_BUTTONS_MARK, ID_SPAM_ACTION_BUTTONS_MOVE, and txtMailbox.
void ConfigSpamcheck::slotChanged () [private, slot]
Connected with the configuration items. Calls the slot changed() of KCModule to notify the dialog about the change.
Definition at line 167 of file configspamcheck.cpp.
Referenced by defaults().
void ConfigSpamcheck::slotActionChanged (int index) [private, slot]
Connected with combobox cmbAction. Enables or disables additional widgets for action configuration.
Parameters:
index position (index) of the selected action
Definition at line 172 of file configspamcheck.cpp.
References btnMailboxWizard, DEFAULT_FILTER_ACTION_MOVE_MAILBOX, ID_SPAM_ACTION_BUTTONS_MOVE, and txtMailbox.
Referenced by defaults(), and load().
void ConfigSpamcheck::slotOpenMailBoxWizard () [private, slot]
Connected with button btnMailboxWizard. Opens a wizard to configure the mailbox
Definition at line 187 of file configspamcheck.cpp.
References txtMailbox.
void ConfigSpamcheck::slotTestSpamAssassin () [private, slot]
Connected with btnTest. Tests whether SpamAssassin is running and shows a message box containing the result. Enables or disables the action widgets.
Definition at line 224 of file configspamcheck.cpp.
References gboxAction, and isSpamAssassinRunning().
bool ConfigSpamcheck::isSpamAssassinRunning () const [protected]
Looks for a running spamd daemon of SpamAssassin.
Returns:
TRUE - SpamAssassin is running
Definition at line 199 of file configspamcheck.cpp.
References NAME_SPAMASSASSIN_DAEMON.
Referenced by slotTestSpamAssassin().
Member Data Documentation
KSharedConfigPtr ConfigSpamcheck::config [private]
Connector to the configuration file
Definition at line 104 of file configspamcheck.h.
Referenced by load(), and save().
KPushButton* ConfigSpamcheck::btnTest [private]
Button to test for a running SpamAssassin
Definition at line 109 of file configspamcheck.h.
KComboBox* ConfigSpamcheck::cmbAction [private]
Combobox to select the action for spam.
Definition at line 114 of file configspamcheck.h.
Referenced by defaults(), load(), and save().
KLineEdit* ConfigSpamcheck::txtMailbox [private]
If selected, the spam mails will be moved to the mailbox which is written in this edit line.
Definition at line 119 of file configspamcheck.h.
Referenced by defaults(), load(), save(), slotActionChanged(), and slotOpenMailBoxWizard().
KPushButton* ConfigSpamcheck::btnMailboxWizard [private]
This button opens a wizard which will help to get the right mailbox
Definition at line 124 of file configspamcheck.h.
Referenced by slotActionChanged().
QGroupBox* ConfigSpamcheck::gboxAction [private]
Contains the widgets of action configuration.
Definition at line 129 of file configspamcheck.h.
Referenced by slotTestSpamAssassin().
The documentation for this class was generated from the following files:
src/configspamcheck.h
src/configspamcheck.cpp