KShowmail: Account Class Reference
Account Class Reference
This class represents an POP3-Account.
#include <account.h>
Signals
void sigDeleteReady (QString account)
Will be emitted when all selected mails are deleted.
void sigShowBodiesReady (QString account)
Will be emitted when the bodies of all selected mails are downloaded and shown.
void sigConfigChanged ()
Will be emitted when the settings have been changed.
void sigMessageWindowOpened ()
Will be emitted, when a window to show a message was opened.
void sigMessageWindowClosed ()
Will be emitted, when a window to show a message was closed.
void sigRefreshReady (QString account)
Will be emitted, when the mail list was refreshed.
Public Member Functions
Account (QString name, AccountList *accountList, QObject *parent)
Constructor.
~Account ()
Destructor.
void print () const
Prints all data of this account to stdout.
QString getName () const
Returns the account name.
bool isActive () const
Returns whether the account is active.
void setActive (bool active)
Sets the account active.
void load ()
Loads the options of this account from the application config.
void refreshMailList (FilterLog *log=NULL)
Refreshes the mail list.
QString getPassword () const
Gets the account password.
void setPassword (const QString &password)
Sets the account password.
void setHost (const QString &host)
Sets the host name.
QString getHost () const
Returns the hostname.
void setProtocol (const QString &protocol)
Sets the protocol.
QString getProtocol (bool upperCase=false) const
Returns the protocol.
void setPort (unsigned short int port)
Sets the port.
unsigned short int getPort () const
Returns the port number.
void setUser (const QString &user)
Sets the user.
QString getUser () const
Returns the user name.
void setPasswordStorage (int storage)
Sets the password storage type.
int getPasswordStorage () const
Returns the password storage type. The Constants are defined in constants.h.
Types::AccountState_Type getState ()
Returns the state of the account.
bool isUnsecureLoginAllowed () const
Return whether an unsecure login is allowed.
int getNumberMails () const
Returns the number of mails if this account is active. Otherwise returns 0.
void addMailToDelete (int number)
Adds a mail number to the list of mails to delete.
void addMailToShow (int number)
Adds a mail number to the list of mails to show.
virtual void deleteMails ()
Deletes mails which are listed in mailsToDelete.
int numberDeletedMailsLastRefresh ()
Returns the number of deleted mails by last refresh.
int numberDeletedMailsStart ()
Returns the number of deleted mails since start.
int numberMovedMailsLastRefresh ()
Returns the number of moved mails by last refresh.
int numberMovedMailsStart ()
Returns the number of moved mails since start.
int numberIgnoredMails ()
Returns the number of ignored mails by last refresh.
void reloadFilterSettings ()
Reloads the settings of the filters.
void saveOptions (QDomDocument &doc, QDomElement &parent)
Saves the stored mails into the given DOM document.
void showMails ()
Downloads and shows the bodies of mails in mailsToShow.
int getNumberNewMails ()
Returns the number of new mails.
long getTotalSize () const
Returns the total size (bytes) of all mails.
QString getTotalSizeUnit () const
Returns the total size of all mails with unit.
void readStoredMails (QDomElement &parent)
Gets the stored mails.
int compare (Account *other, AccountSort_Type property)
Compares this account with other and returns an integer less than, equal to, or greater than zero if this account is less than, equal to, or greater than other.
QList< Mail > getAllMails () const
Returns a list which contains the pointers to all mails.
void cancelTask ()
Cancels the current running task.
AccountViewItem getViewItem ()
Returns a appropriate view item.
Protected Slots
virtual void slotConnected ()
Connected with signal connected of the socket. Will be invoked after the socket has connected the host.
virtual void slotHostFound ()
Connected with signal hostFound of the socket. Will be invoked after the socket has done the DNS lookup.
void slotSocketError (KTcpSocket::Error errorCode)
Connected with signal error of the socket. Will be invoked, when an socket error occures.
void slotSSLError (const QList< KSslError > &errors)
Connected with signale sslErrors of the socket.
void slotReadFirstServerMessage ()
Reads the first message send by server.
void slotCapabilitiesResponse ()
Reads the capabilities from the server.
void slotAuthMechResponse ()
Connected with the signal readyRead of the socket by getAuthMech(). Analyzes the response and sets the authentication mechanism flags of this account.
void slotCommitResponse ()
Connected with signal readyRead of the socket by commit(). Analyzes the commit response of the server.
void slotLoginUserResponse ()
Received the response of the USER command during login.
void slotLoginPasswdResponse ()
Received the response of the PASS command during login.
void slotLoginApopResponse ()
Receives the response of a login using APOP.
void slotUIDListResponse ()
Reiceves the response of the UIDL command, which gets the UID's of the mails.
void slotMailSizesResponse ()
Receives the response of the LIST command, which gets the numbers and sizes of the mails.
void slotGetHeaderResponse ()
Receives the header requested by getNextHeader().
void slotMailDeleted ()
Removes the deleted mail from the internal mail list (m_pshowrecord).
void slotBodyDownloaded ()
Opens a window (class ShowMailDialog) with the downloaded mail body.
void slotMailDownloadedForAction ()
Downloads a mail to write it into a mailbox or do a spam check.
void slotCommitBeforeRefreshDone ()
Restarts a second refresh cycle after a deletion performed by the filter.
void slotTimeout ()
Connected with the timeout timer.
void slotStartTLSResponse ()
Receives the response of the STLS command.
Protected Member Functions
void init ()
Initiate the account.
bool hasPassword () const
Returns whether a password is stored.
bool assertPassword (bool force=false)
Opens a dialog to ask for a password, stores it temporarily in the account settings and emits the signal sigConfigChanged.
void doConnect ()
Establishes a connection to the server.
void closeConnection ()
Closes the connection.
void initBeforeConnect ()
Initiates the account to do a connect.
void handleError (QString error)
Shows the given error, sets the state to idle and emits a ready signal if necessary.
QStringList readfromSocket (bool singleLine)
Reads all data from the socket.
void sendCommand (const QString &command)
Sends a command to the server.
void getCapabilities ()
Gets the capabilities from the server. Sends the CAPA-command connect the socket with slot slotReceiveCapabilities().
void printServerMessage (QStringList &text) const
Prints the a text received from the server to stdout.
bool isPositiveServerMessage (QStringList &message) const
Returns whether the server answer is positive or negative.
void getAuthMech ()
Sends the command to get the authentication mechanism of this server.
virtual void commit ()
Sends the commit command to end the session.
void finishTask ()
Finishes the running task (Refreshing, Deleting, ...).
void loginUser ()
Sends the login name.
void loginPasswd ()
Sends the password for login.
void loginApop ()
Initiates a login using APOP.
QString removeStatusIndicator (const QString &message)
Removes the status indicator from a single line server message.
void removeStatusIndicator (QStringList *response)
If the first line of the server response is the status indicator (+OK or -ERR), this methode will remove this line.
void removeEndOfResponseMarker (QStringList *response)
If the last line of the server response is the end of response marker, this methode will remove this line.
void getUIDList ()
Sends the UIDL command to get a list of the mail UID's.
void swapMailLists ()
Copies the pointer to the temporary list to the mail list.
void getMailSizes ()
Sends the LIST command to get a list of mail sizes.
void getHeaders ()
Gets the headers of the new mails from the server.
virtual void getNextHeader ()
Get the header of the first mail in newMails.
bool isNegativeResponse (const QString &response)
Returns whether the given string is a negative server response.
void copyHeaders ()
Copies the known headers of the old mails from the old mail list to the new one.
void deleteNextMail ()
Deletes the first mail of MailsToDelete.
void showNextMail ()
Shows the body of the first mail in MailsToShow.
void doDownloadActions ()
Does all filter actions for which we have to download the mails.
void getNextMailForDownloadActions ()
Gets the body of the first mail in MailsToDownload.
void applyFiltersDeleted ()
If there are mails to delete by filters applyFilters will call the regular deletion cycle of this class with set byFilter-flag.
void commitBeforeRefresh ()
Send a commit and restart the refresh cycle.
void applyFilters ()
Applies the filters to the mails in the mail list.
bool writeToMailBox (const QStringList &mail, const QString &box)
Writes the given mail into the mailbox.
bool isMailDir (const QDir &path)
Returns whether the given directory is a maildir directory.
bool isSpam (QStringList mail) const
Forwards the given mail to SpamAssassin and returns the test result.
bool isSpamAssassinRunning () const
Looks for a running spamd daemon of SpamAssassin.
void startTLS ()
Invites the server to crypt using TLS (STARTTLS).
Private Attributes
QString name
Name of this account.
bool active
TRUE - account is active; FALSE - account is not active.
TransferSecurity_Type transferSecurity
Type of the transfer security.
KUrl url
Uniform Resource Locator of the account on the mail server.
int passwordStorage
Type of password storage.
MailList * mails
The mail container.
MailList * tempMailList
While refreshing, this mail list instance will be used to build a new mail list. After that this pointer will be assigned to maillist.
KTcpSocket * socket
The socket. Handles all server operations.
AccountList * accountList
Pointer to the account list object.
bool quitSent
TRUE - the QUIT command was sent to the server. Normally set by the commit methode.
QTimer * timeoutTimer
This timer kills a running operation after the preset time.
Types::AccountState_Type state
State of the account.
bool apopAvail
APOP available.
bool dontUseAPOP
Is set to TRUE by slotLoginAPOPResponse if the first login with APOP is failed.
QString apopTimestamp
Timestamp for APOP sent with the server greeting.
bool allowUnsecureLogin
TRUE - unsafe login is allowed if a secure login failed.
bool filterApplied
This is a flag whether the filters was applied during a refresh cycle.
bool refreshPerformedByFilters
This flag is set by applyFiltersDeleted() to indicate the refresh cycle is the second one after a deletion which was performed by filters.
MailNumberList_Type newMails
Contains the numbers of new mails.
MailNumberList_Type mailsToDelete
Contains the numbers of mails which will be deleted.
MailToDownloadMap_Type mailsToDownload
Contains the numbers of the mails shall be moved for actions like moving to mailbox or spam check.
MailNumberList_Type mailsToShow
Contains the numbers of mails for which the bodies will be shown.
FilterLog * fLog
Pointer to the filter log.
int nmbDeletedMailsLastRefresh
Number of deleted mails by last refresh.
int nmbMovedMailsLastRefresh
Number of moved mails by last refresh.
int nmbMovedMailsLastStart
Number of moved mails since start.
int nmbIgnoredMails
Number of ignored mails by last refresh.
int moveCounter
Counter for moving to create an unique file name.
int nmbDeletedMailsLastStart
Number of deleted mails since start.
bool downloadActionsInvoked
This flag is set to TRUE by applyFilters() to indicate the mailbodies are downloading and writing to the mailboxes or spam checking.
HeaderFilter headerFilter
Every account has is own header filter instance.
bool deletionPerformedByFilters
This flag is set by applyFilters() to indicate the deletion cycle is performed by filters and not by user.
QString spamMailbox
Mailbox for Spam, if configured.
FilterAction_Type spamAction
Action which shall be done, if the mail is Spam.
bool dontHandleError
TRUE - the error will not be handled by slotSocketError.
bool informAboutErrors
TRUE - informs the user about connection errors.
int timeOutTime
Seconds to Timeout.
bool supportsStartTLS
TRUE - the server supports StartTLS.
Detailed Description
This class represents an POP3-Account.
Definition at line 164 of file account.h.
Constructor & Destructor Documentation
Account::Account (QString name, AccountList * accountList, QObject * parent)
Constructor.
Parameters:
name name of this account
accountList pointer to the parent account list
parent parent object
Definition at line 21 of file account.cpp.
References init(), mails, slotConnected(), slotHostFound(), slotSocketError(), slotSSLError(), slotTimeout(), socket, and timeoutTimer.
Account::~Account ()
Destructor.
Definition at line 47 of file account.cpp.
References mails.
Member Function Documentation
void Account::print () const
Prints all data of this account to stdout.
Definition at line 57 of file account.cpp.
References getName(), isActive(), mails, MailList::print(), and url.
Referenced by AccountList::print().
QString Account::getName () const
Returns the account name.
Returns:
account name
Definition at line 52 of file account.cpp.
References name.
Referenced by applyFilters(), assertPassword(), closeConnection(), compare(), finishTask(), getViewItem(), handleError(), AccountList::hasAccount(), load(), print(), readfromSocket(), refreshMailList(), saveOptions(), sendCommand(), slotAuthMechResponse(), slotBodyDownloaded(), slotGetHeaderResponse(), slotMailDeleted(), slotMailDownloadedForAction(), KShowmail::slotSetupAccount(), slotSSLError(), slotStartTLSResponse(), and slotUIDListResponse().
bool Account::isActive () const
Returns whether the account is active.
Returns:
TRUE - account is active; FALSE - account is not active
Definition at line 99 of file account.cpp.
References active.
Referenced by compare(), getAllMails(), getNumberMails(), getViewItem(), print(), refreshMailList(), and saveOptions().
void Account::setActive (bool active)
Sets the account active.
Parameters:
active TRUE - active account; FALSE - deactivate account
Definition at line 104 of file account.cpp.
void Account::load ()
Loads the options of this account from the application config.
Definition at line 108 of file account.cpp.
References active, allowUnsecureLogin, CONFIG_ENTRY_ACCOUNT_ACTIVE, CONFIG_ENTRY_ACCOUNT_ALLOW_UNSECURE_LOGIN, CONFIG_ENTRY_ACCOUNT_PASSWORD, CONFIG_ENTRY_ACCOUNT_PASSWORD_STORAGE, CONFIG_ENTRY_ACCOUNT_PORT, CONFIG_ENTRY_ACCOUNT_PROTOCOL, CONFIG_ENTRY_ACCOUNT_SECTRANSFER, CONFIG_ENTRY_ACCOUNT_SERVER, CONFIG_ENTRY_ACCOUNT_USER, CONFIG_ENTRY_SHOW_CONNECTION_ERRORS, CONFIG_ENTRY_SPAMCHECK_ACTION, CONFIG_ENTRY_SPAMCHECK_MOVE_MAILBOX, CONFIG_ENTRY_TIMEOUT_TIME, CONFIG_GROUP_GENERAL, CONFIG_GROUP_SPAMCHECK, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_FILE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_KWALLET, CONFIG_VALUE_ACCOUNT_SECTRANSFER_NONE, CONFIG_VALUE_ACCOUNT_SECTRANSFER_SSL, CONFIG_VALUE_ACCOUNT_SECTRANSFER_TLS, CONFIG_VALUE_SPAMCHECK_ACTION_DELETE, CONFIG_VALUE_SPAMCHECK_ACTION_MARK, CONFIG_VALUE_SPAMCHECK_ACTION_MOVE, Encryption::decrypt(), DEFAULT_ACCOUNT_ACTIVE, DEFAULT_ACCOUNT_ALLOW_UNSECURE_LOGIN, DEFAULT_ACCOUNT_PASSWORD, DEFAULT_ACCOUNT_PASSWORD_STORAGE, DEFAULT_ACCOUNT_PORT_POP3, DEFAULT_ACCOUNT_PROTOCOL, DEFAULT_ACCOUNT_SECTRANSFER, DEFAULT_ACCOUNT_SERVER, DEFAULT_ACCOUNT_USER, DEFAULT_SHOW_CONNECTION_ERRORS, DEFAULT_SPAMCHECK_ACTION, DEFAULT_SPAMCHECK_ACTION_MOVE_MAILBOX, DEFAULT_TIMEOUT_TIME, Types::FActDelete, Types::FActMark, Types::FActMove, getName(), KWalletAccess::getPassword(), informAboutErrors, passwordStorage, setHost(), setPassword(), setPort(), setProtocol(), setUser(), spamAction, spamMailbox, timeOutTime, transferSecurity, Types::TransSecNone, Types::TransSecSSL, and Types::TransSecTLS.
Referenced by AccountList::loadSetup().
void Account::refreshMailList (FilterLog * log = NULL)
Refreshes the mail list.
This just starts the refresh and returns after then. When the refresh is ready, the signal sigRefreshReady will be emitted.
Parameters:
log pointer to the filter log
See also:
sigRefreshReady
Definition at line 173 of file account.cpp.
References Types::AccountRefreshing, assertPassword(), doConnect(), fLog, getName(), isActive(), name, nmbDeletedMailsLastRefresh, nmbIgnoredMails, nmbMovedMailsLastRefresh, refreshPerformedByFilters, sigRefreshReady(), state, and tempMailList.
Referenced by AccountList::refreshMailLists(), and slotCommitBeforeRefreshDone().
QString Account::getPassword () const
Gets the account password.
Returns:
password
Definition at line 225 of file account.cpp.
References url.
Referenced by loginApop(), and loginPasswd().
void Account::setPassword (const QString & password)
Sets the account password.
Parameters:
password new password
Definition at line 230 of file account.cpp.
References url.
Referenced by assertPassword(), and load().
void Account::setHost (const QString & host)
Sets the host name.
Parameters:
host host name
Definition at line 235 of file account.cpp.
References url.
Referenced by load().
QString Account::getHost () const
Returns the hostname.
Returns:
the name of the host or QString::null if no host is set
Definition at line 260 of file account.cpp.
References url.
Referenced by compare(), doConnect(), getViewItem(), sendCommand(), slotBodyDownloaded(), slotCommitResponse(), slotGetHeaderResponse(), slotMailDeleted(), slotMailDownloadedForAction(), slotMailSizesResponse(), slotReadFirstServerMessage(), slotSocketError(), and slotStartTLSResponse().
void Account::setProtocol (const QString & protocol)
Sets the protocol.
Parameters:
protocol the protocol
Definition at line 240 of file account.cpp.
References url.
Referenced by load().
QString Account::getProtocol (bool upperCase = false) const
Returns the protocol.
Parameters:
upperCase TRUE - transforms the protocol string to upper case
Returns:
protocol
Definition at line 265 of file account.cpp.
References url.
void Account::setPort (unsigned short int port)
Sets the port.
Parameters:
port the port
Definition at line 245 of file account.cpp.
References url.
Referenced by load().
unsigned short int Account::getPort () const
Returns the port number.
Returns:
port number
Definition at line 273 of file account.cpp.
References url.
Referenced by doConnect().
void Account::setUser (const QString & user)
Sets the user.
Parameters:
user username
Definition at line 250 of file account.cpp.
References url.
Referenced by load().
QString Account::getUser () const
Returns the user name.
Returns:
the user name or QString::null if there is no user name
Definition at line 255 of file account.cpp.
References url.
Referenced by compare(), getViewItem(), loginApop(), and loginUser().
void Account::setPasswordStorage (int storage)
Sets the password storage type.
The Constants are defined in constants.h
Parameters:
storage type of password storage; valid values are: CONFIG_VALUE_ACCOUNT_PASSWORD_DONT_SAVE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_FILE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_KWALLET
Definition at line 340 of file account.cpp.
References CONFIG_VALUE_ACCOUNT_PASSWORD_DONT_SAVE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_FILE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_KWALLET, DEFAULT_ACCOUNT_PASSWORD_STORAGE, and passwordStorage.
int Account::getPasswordStorage () const
Returns the password storage type. The Constants are defined in constants.h.
Returns:
type of password storage; valid values are: CONFIG_VALUE_ACCOUNT_PASSWORD_DONT_SAVE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_FILE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_KWALLET
Definition at line 353 of file account.cpp.
References passwordStorage.
Types::AccountState_Type Account::getState ()
Returns the state of the account.
Returns:
account state
Definition at line 1153 of file account.cpp.
References state.
Referenced by slotLoginApopResponse(), and slotLoginPasswdResponse().
bool Account::isUnsecureLoginAllowed () const
Return whether an unsecure login is allowed.
Returns:
TRUE - unsecure login is allowed
Definition at line 1158 of file account.cpp.
References allowUnsecureLogin.
int Account::getNumberMails () const
Returns the number of mails if this account is active. Otherwise returns 0.
Returns:
number of mails or 0
Definition at line 1617 of file account.cpp.
References MailList::getNumberMails(), isActive(), and mails.
Referenced by compare(), and getViewItem().
void Account::addMailToDelete (int number)
Adds a mail number to the list of mails to delete.
The number is the mail number given by the mail server.
Parameters:
number mail number
See also:
mailsToDelete
Definition at line 1624 of file account.cpp.
References mailsToDelete.
void Account::addMailToShow (int number)
Adds a mail number to the list of mails to show.
The number is the mail number given by the mail server.
Parameters:
number mail number
See also:
mailsToShow
Definition at line 1629 of file account.cpp.
References mailsToShow.
void Account::deleteMails () [virtual]
Deletes mails which are listed in mailsToDelete.
This just starts the deletion and returns after then. When the deletion is ready the signal sigDeleteReady will be emitted.
Definition at line 1634 of file account.cpp.
References Types::AccountDeleting, assertPassword(), doConnect(), mailsToDelete, name, sigDeleteReady(), and state.
int Account::numberDeletedMailsLastRefresh ()
Returns the number of deleted mails by last refresh.
Returns:
number of deleted mails by last refresh
Definition at line 1831 of file account.cpp.
References nmbDeletedMailsLastRefresh.
int Account::numberDeletedMailsStart ()
Returns the number of deleted mails since start.
Returns:
number of deleted mails since start
Definition at line 1836 of file account.cpp.
References nmbDeletedMailsLastStart.
int Account::numberMovedMailsLastRefresh ()
Returns the number of moved mails by last refresh.
Returns:
number of moved mails by last refresh
Definition at line 1841 of file account.cpp.
References nmbMovedMailsLastRefresh.
int Account::numberMovedMailsStart ()
Returns the number of moved mails since start.
Returns:
number of moved mails since start
Definition at line 1846 of file account.cpp.
References nmbMovedMailsLastStart.
int Account::numberIgnoredMails ()
Returns the number of ignored mails by last refresh.
Returns:
number of ignored mails by last refresh
Definition at line 1851 of file account.cpp.
References nmbIgnoredMails.
void Account::reloadFilterSettings ()
Reloads the settings of the filters.
It just calls the load() methode of the header filter.
Definition at line 1856 of file account.cpp.
References headerFilter, and HeaderFilter::load().
void Account::saveOptions (QDomDocument & doc, QDomElement & parent)
Saves the stored mails into the given DOM document.
It doesn't create a new DOM element but used the given one. Saves the setup into the application config.
Parameters:
doc DOM document which contains all application settings, mails and account settings
parent DOM element in which all settings and mails of this account will be saved
Definition at line 2072 of file account.cpp.
References ATTRIBUTE_ACCOUNT_NAME, CONFIG_ENTRY_ACCOUNT_ACTIVE, getName(), isActive(), mails, and MailList::saveMails().
void Account::showMails ()
Downloads and shows the bodies of mails in mailsToShow.
This just starts the download and returns after then. When the download is ready and the body is shown the sigShowBodiesReady will be emitted.
See also:
mailsToShow
Definition at line 2086 of file account.cpp.
References Types::AccountDownloading, assertPassword(), doConnect(), mailsToShow, name, sigShowBodiesReady(), and state.
int Account::getNumberNewMails ()
Returns the number of new mails.
Returns:
number of new mails
Definition at line 2267 of file account.cpp.
References MailList::getNumberNewMails(), and mails.
long Account::getTotalSize () const
Returns the total size (bytes) of all mails.
Returns:
total size
Definition at line 2272 of file account.cpp.
References MailList::getTotalSize(), and mails.
Referenced by compare(), getTotalSizeUnit(), and getViewItem().
QString Account::getTotalSizeUnit () const
Returns the total size of all mails with unit.
Definition at line 2276 of file account.cpp.
References getTotalSize().
void Account::readStoredMails (QDomElement & parent)
Gets the stored mails.
Parameters:
parent DOM element which contains the mails of this account
Definition at line 2340 of file account.cpp.
References mails, and MailList::readStoredMails().
Referenced by AccountList::readStoredMails().
int Account::compare (Account * other, AccountSort_Type property)
Compares this account with other and returns an integer less than, equal to, or greater than zero if this account is less than, equal to, or greater than other.
Parameters:
other other account
property the account property which will be compared
Definition at line 2346 of file account.cpp.
References Types::AccSortActive, Types::AccSortName, Types::AccSortNrMess, Types::AccSortServer, Types::AccSortSize, Types::AccSortUser, getHost(), getName(), getNumberMails(), getTotalSize(), getUser(), and isActive().
QList< Mail > Account::getAllMails () const
Returns a list which contains the pointers to all mails.
Returns:
all mails
Definition at line 2400 of file account.cpp.
References MailList::getAllMails(), isActive(), and mails.
void Account::cancelTask ()
Cancels the current running task.
Definition at line 2413 of file account.cpp.
References Types::AccountIdle, handleError(), socket, and state.
AccountViewItem Account::getViewItem ()
Returns a appropriate view item.
Returns:
view item
Definition at line 2489 of file account.cpp.
References getHost(), getName(), getNumberMails(), getTotalSize(), getUser(), and isActive().
void Account::init () [protected]
Initiate the account.
Definition at line 73 of file account.cpp.
References Types::AccountIdle, active, deletionPerformedByFilters, dontHandleError, downloadActionsInvoked, filterApplied, moveCounter, nmbDeletedMailsLastRefresh, nmbDeletedMailsLastStart, nmbIgnoredMails, nmbMovedMailsLastRefresh, nmbMovedMailsLastStart, and state.
Referenced by Account().
bool Account::hasPassword () const [protected]
Returns whether a password is stored.
Returns:
TRUE - there is password stored; FALSE - no password stored
Definition at line 220 of file account.cpp.
References url.
Referenced by assertPassword().
bool Account::assertPassword (bool force = false) [protected]
Opens a dialog to ask for a password, stores it temporarily in the account settings and emits the signal sigConfigChanged.
Does not open a dialog if a password is already stored in the account settings.
Parameters:
force ask for a new password even if a password is stored
Returns:
true - a password is available; false - no password is available
Definition at line 278 of file account.cpp.
References CONFIG_ENTRY_ACCOUNT_PASSWORD, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_FILE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_KWALLET, Encryption::crypt(), getName(), hasPassword(), passwordStorage, KWalletAccess::savePassword(), setPassword(), sigConfigChanged(), and url.
Referenced by deleteMails(), refreshMailList(), and showMails().
void Account::doConnect () [protected]
Establishes a connection to the server.
Definition at line 358 of file account.cpp.
References closeConnection(), getHost(), getPort(), handleError(), initBeforeConnect(), slotReadFirstServerMessage(), socket, transferSecurity, Types::TransSecNone, Types::TransSecSSL, and Types::TransSecTLS.
Referenced by deleteMails(), refreshMailList(), showMails(), and slotLoginApopResponse().
void Account::closeConnection () [protected]
Closes the connection.
Definition at line 389 of file account.cpp.
References getName(), and socket.
Referenced by doConnect(), finishTask(), handleError(), and slotLoginApopResponse().
void Account::initBeforeConnect () [protected]
Initiates the account to do a connect.
Definition at line 398 of file account.cpp.
References apopAvail, deletionPerformedByFilters, dontHandleError, dontUseAPOP, downloadActionsInvoked, filterApplied, quitSent, supportsStartTLS, timeOutTime, and timeoutTimer.
Referenced by doConnect().
void Account::handleError (QString error) [protected]
Shows the given error, sets the state to idle and emits a ready signal if necessary.
Parameters:
error the error message
Definition at line 480 of file account.cpp.
References Types::AccountDeleting, Types::AccountDownloading, Types::AccountIdle, Types::AccountRefreshing, closeConnection(), getName(), informAboutErrors, mailsToDelete, mailsToDownload, mailsToShow, sigDeleteReady(), sigMessageWindowClosed(), sigMessageWindowOpened(), sigRefreshReady(), sigShowBodiesReady(), state, and timeoutTimer.
Referenced by cancelTask(), doConnect(), sendCommand(), slotBodyDownloaded(), slotCapabilitiesResponse(), slotCommitResponse(), slotGetHeaderResponse(), slotLoginApopResponse(), slotLoginPasswdResponse(), slotLoginUserResponse(), slotMailDeleted(), slotMailDownloadedForAction(), slotMailSizesResponse(), slotReadFirstServerMessage(), slotSocketError(), slotTimeout(), and slotUIDListResponse().
QStringList Account::readfromSocket (bool singleLine) [protected]
Reads all data from the socket.
Parameters:
singleLine TRUE - the response will be a single line; FALSE - the response has more lines
Returns:
read text
Definition at line 516 of file account.cpp.
References dontHandleError, POP3Constants::END_MULTILINE_RESPONSE(), getName(), isNegativeResponse(), socket, transferSecurity, Types::TransSecSSL, and Types::TransSecTLS.
Referenced by slotAuthMechResponse(), slotBodyDownloaded(), slotCapabilitiesResponse(), slotCommitResponse(), slotGetHeaderResponse(), slotLoginApopResponse(), slotLoginPasswdResponse(), slotLoginUserResponse(), slotMailDeleted(), slotMailDownloadedForAction(), slotMailSizesResponse(), slotReadFirstServerMessage(), slotStartTLSResponse(), and slotUIDListResponse().
void Account::sendCommand (const QString & command) [protected]
Sends a command to the server.
Parameters:
command the command to send
Definition at line 740 of file account.cpp.
References getHost(), getName(), handleError(), and socket.
Referenced by commit(), commitBeforeRefresh(), deleteNextMail(), getAuthMech(), getCapabilities(), getMailSizes(), getNextHeader(), getNextMailForDownloadActions(), getUIDList(), loginApop(), loginPasswd(), loginUser(), showNextMail(), and startTLS().
void Account::getCapabilities () [protected]
Gets the capabilities from the server. Sends the CAPA-command connect the socket with slot slotReceiveCapabilities().
See also:
slotCapabilitiesResponse
Definition at line 770 of file account.cpp.
References POP3Constants::CAPA_REQUEST(), sendCommand(), slotCapabilitiesResponse(), and socket.
Referenced by slotReadFirstServerMessage().
void Account::printServerMessage (QStringList & text) const [protected]
Prints the a text received from the server to stdout.
Parameters:
text server message
Definition at line 821 of file account.cpp.
bool Account::isPositiveServerMessage (QStringList & message) const [protected]
Returns whether the server answer is positive or negative.
Parameters:
message server message
Returns:
TRUE - positive answer; FALSE - negative answer
Definition at line 836 of file account.cpp.
References POP3Constants::RESPONSE_POSITIVE().
Referenced by slotAuthMechResponse(), slotBodyDownloaded(), slotCapabilitiesResponse(), slotCommitResponse(), slotGetHeaderResponse(), slotLoginApopResponse(), slotLoginPasswdResponse(), slotLoginUserResponse(), slotMailDeleted(), slotMailDownloadedForAction(), slotMailSizesResponse(), slotReadFirstServerMessage(), slotStartTLSResponse(), and slotUIDListResponse().
void Account::getAuthMech () [protected]
Sends the command to get the authentication mechanism of this server.
Connects the signal readyRead of the socket with the slot slotAuthMechResponse(). If the socket has got the server response it will send this signal
See also:
slotAuthMechResponse()
Definition at line 848 of file account.cpp.
References POP3Constants::AUTH_REQUEST(), sendCommand(), slotAuthMechResponse(), and socket.
Referenced by slotCapabilitiesResponse().
void Account::commit () [protected, virtual]
Sends the commit command to end the session.
Connects the signal readyRead of the socket with the slot slotCommitResponse().
See also:
slotCommitResponse()
Definition at line 912 of file account.cpp.
References POP3Constants::COMMIT(), finishTask(), quitSent, sendCommand(), slotCommitResponse(), and socket.
Referenced by applyFilters(), deleteNextMail(), showNextMail(), slotBodyDownloaded(), slotLoginApopResponse(), slotLoginPasswdResponse(), slotMailDeleted(), and swapMailLists().
void Account::finishTask () [protected]
Finishes the running task (Refreshing, Deleting, ...).
Emits the proper ready signal and closes the connection
See also:
closeConnection()
sigDeleteReady()
sigRefreshReady()
sigShowBodiesReady()
Definition at line 933 of file account.cpp.
References Types::AccountDeleting, Types::AccountDownloading, Types::AccountIdle, Types::AccountRefreshing, closeConnection(), getName(), mailsToDelete, mailsToDownload, mailsToShow, sigDeleteReady(), sigRefreshReady(), sigShowBodiesReady(), state, and timeoutTimer.
Referenced by commit(), commitBeforeRefresh(), slotAuthMechResponse(), slotBodyDownloaded(), slotCapabilitiesResponse(), slotCommitResponse(), slotGetHeaderResponse(), slotLoginApopResponse(), slotLoginPasswdResponse(), slotLoginUserResponse(), slotMailDeleted(), slotMailDownloadedForAction(), slotMailSizesResponse(), slotReadFirstServerMessage(), slotSSLError(), slotStartTLSResponse(), and slotUIDListResponse().
void Account::loginUser () [protected]
Sends the login name.
The response will be received by slotLoginUserResponse().
See also:
slotLoginUserResponse
Definition at line 984 of file account.cpp.
References getUser(), POP3Constants::LOGIN_USER(), sendCommand(), slotLoginUserResponse(), and socket.
Referenced by slotAuthMechResponse(), and slotStartTLSResponse().
void Account::loginPasswd () [protected]
Sends the password for login.
The response will be received by slotLoginPasswdResponse().
See also:
slotLoginPasswdResponse
Definition at line 1018 of file account.cpp.
References getPassword(), POP3Constants::LOGIN_PASSWD(), sendCommand(), slotLoginPasswdResponse(), and socket.
Referenced by slotLoginUserResponse().
void Account::loginApop () [protected]
Initiates a login using APOP.
The response will be received by slotLoginApopResponse().
See also:
slotLoginApopResponse()
Definition at line 1077 of file account.cpp.
References apopTimestamp, getPassword(), getUser(), POP3Constants::LOGIN_APOP(), sendCommand(), slotLoginApopResponse(), and socket.
Referenced by slotAuthMechResponse(), and slotStartTLSResponse().
QString Account::removeStatusIndicator (const QString & message) [protected]
Removes the status indicator from a single line server message.
Parameters:
message server message
Returns:
server message without status indicator
Definition at line 1058 of file account.cpp.
References POP3Constants::RESPONSE_NEGATIVE(), and POP3Constants::RESPONSE_POSITIVE().
Referenced by slotAuthMechResponse(), slotBodyDownloaded(), slotCapabilitiesResponse(), slotGetHeaderResponse(), slotLoginApopResponse(), slotLoginPasswdResponse(), slotLoginUserResponse(), slotMailDownloadedForAction(), slotMailSizesResponse(), and slotUIDListResponse().
void Account::removeStatusIndicator (QStringList * response) [protected]
If the first line of the server response is the status indicator (+OK or -ERR), this methode will remove this line.
Definition at line 1134 of file account.cpp.
References POP3Constants::RESPONSE_NEGATIVE(), and POP3Constants::RESPONSE_POSITIVE().
void Account::removeEndOfResponseMarker (QStringList * response) [protected]
If the last line of the server response is the end of response marker, this methode will remove this line.
Definition at line 1276 of file account.cpp.
References POP3Constants::END_MULTILINE_RESPONSE().
Referenced by slotAuthMechResponse(), slotBodyDownloaded(), slotCapabilitiesResponse(), slotGetHeaderResponse(), slotMailDownloadedForAction(), slotMailSizesResponse(), and slotUIDListResponse().
void Account::getUIDList () [protected]
Sends the UIDL command to get a list of the mail UID's.
The response will be received by the slotUIDListResponse.
See also:
slotUIDListResponse
Definition at line 1163 of file account.cpp.
References sendCommand(), slotUIDListResponse(), socket, and POP3Constants::UID_LIST().
Referenced by slotLoginApopResponse(), and slotLoginPasswdResponse().
void Account::swapMailLists () [protected]
Copies the pointer to the temporary list to the mail list.
The temporary list will be the current mail list.
Definition at line 1293 of file account.cpp.
References applyFilters(), commit(), filterApplied, headerFilter, HeaderFilter::isActive(), mails, refreshPerformedByFilters, and tempMailList.
Referenced by copyHeaders(), and slotUIDListResponse().
void Account::getMailSizes () [protected]
Sends the LIST command to get a list of mail sizes.
The response will be received by slotMailListResponse.
See also:
slotMailSizesResponse
Definition at line 1396 of file account.cpp.
References POP3Constants::MAIL_LIST(), sendCommand(), slotMailSizesResponse(), and socket.
Referenced by slotUIDListResponse().
void Account::getHeaders () [protected]
Gets the headers of the new mails from the server.
Definition at line 1504 of file account.cpp.
References copyHeaders(), MailList::getNewMails(), getNextHeader(), newMails, and tempMailList.
Referenced by slotMailSizesResponse().
void Account::getNextHeader () [protected, virtual]
Get the header of the first mail in newMails.
After a successful download this mail will be removed from the list by slotHeaderDownloaded() and this method will be invoked again. If the list is empty, it will call copyHeaders() to get the known headers from the old mail list.
See also:
copyHeaders()
slotHeaderDownloaded()
Definition at line 1519 of file account.cpp.
References copyHeaders(), POP3Constants::GET_HEADER(), newMails, sendCommand(), slotGetHeaderResponse(), and socket.
Referenced by getHeaders(), and slotGetHeaderResponse().
bool Account::isNegativeResponse (const QString & response) [protected]
Returns whether the given string is a negative server response.
Parameters:
response server response to check
Returns:
TRUE - response is negative
FALSE - response is positive
Definition at line 1586 of file account.cpp.
References POP3Constants::RESPONSE_NEGATIVE().
Referenced by readfromSocket().
void Account::copyHeaders () [protected]
Copies the known headers of the old mails from the old mail list to the new one.
At the end it invokes swapMailLists().
Definition at line 1592 of file account.cpp.
References MailList::getHeaderOf(), MailList::getUIDsOfOldMails(), mails, MailList::setHeader(), swapMailLists(), tempMailList, and Exception::what().
Referenced by getHeaders(), getNextHeader(), and slotGetHeaderResponse().
void Account::deleteNextMail () [protected]
Deletes the first mail of MailsToDelete.
After a successful deletion this mail will be removed from the list by slotMailDeleted() and this method will be invoked again. If the list is empty, it will call commitDelete.
See also:
slotMailDeleted()
MailsToDelete
Definition at line 1660 of file account.cpp.
References applyFiltersDeleted(), commit(), POP3Constants::DELETE(), deletionPerformedByFilters, mailsToDelete, sendCommand(), slotMailDeleted(), and socket.
Referenced by applyFilters(), slotLoginApopResponse(), slotLoginPasswdResponse(), and slotMailDeleted().
void Account::showNextMail () [protected]
Shows the body of the first mail in MailsToShow.
After a successful download and opening of the window this mail will be removed from the list by slotBodyDownloaded() and this method will be invoked again. If the list is empty, it will call commitDownloading().
See also:
commitDownloading()
slotBodyDownloaded()
Definition at line 1684 of file account.cpp.
References commit(), POP3Constants::GET_MAIL(), mailsToShow, sendCommand(), slotBodyDownloaded(), and socket.
Referenced by slotBodyDownloaded(), slotLoginApopResponse(), and slotLoginPasswdResponse().
void Account::doDownloadActions () [protected]
Does all filter actions for which we have to download the mails.
These are: Moving, spam check It doesn't removes they from the server.
Definition at line 1861 of file account.cpp.
References getNextMailForDownloadActions().
Referenced by applyFilters().
void Account::getNextMailForDownloadActions () [protected]
Gets the body of the first mail in MailsToDownload.
After a successful download and writing into the mailbox this mail will be removed from the list by slotMailDownloadedforDownloadActions() and this method will be invoked again. If the list is empty, it will call applyFilters() to continue the filtering.
See also:
applyFilters()
slotMailDownloadedforDownloadActions()
Definition at line 1867 of file account.cpp.
References applyFilters(), POP3Constants::GET_MAIL(), mailsToDownload, sendCommand(), slotMailDownloadedForAction(), and socket.
Referenced by doDownloadActions(), and slotMailDownloadedForAction().
void Account::applyFiltersDeleted () [protected]
If there are mails to delete by filters applyFilters will call the regular deletion cycle of this class with set byFilter-flag.
Therefore the deletion will not branch to commitDeletion() but to this methode. This performs a second refresh cycle to get an effective mail list from the server. This new cycle will not apply the filters again, because the flag filterApplied is set to TRUE.
See also:
applyFilters()
filterApplied
Definition at line 2032 of file account.cpp.
References commitBeforeRefresh(), deletionPerformedByFilters, and refreshPerformedByFilters.
Referenced by deleteNextMail(), and slotMailDeleted().
void Account::commitBeforeRefresh () [protected]
Send a commit and restart the refresh cycle.
We restart the refresh to get a fresh maillist after a deletion performed by the filter. We need a commit before because the mails server only after a commit reorders the mail numbers
Definition at line 2044 of file account.cpp.
References POP3Constants::COMMIT(), finishTask(), quitSent, sendCommand(), slotCommitBeforeRefreshDone(), and socket.
Referenced by applyFiltersDeleted().
void Account::applyFilters () [protected]
Applies the filters to the mails in the mail list.
step of the refresh cycle. Invoked by swapMailLists(). This methode maybe starts a new refresh cycle because after a deletion or moving we need a actual list of mails on the server. To avoid a never-ending loop you must not call this methode during the second refresh cycle. Therefore it sets filterApplied to TRUE.
See also:
filterApplied
applyFiltersDeleted()
Definition at line 1329 of file account.cpp.
References MailList::applyHeaderFilter(), commit(), deleteNextMail(), deletionPerformedByFilters, doDownloadActions(), downloadActionsInvoked, filterApplied, fLog, getName(), headerFilter, mails, mailsToDelete, mailsToDownload, nmbDeletedMailsLastRefresh, nmbDeletedMailsLastStart, and nmbIgnoredMails.
Referenced by getNextMailForDownloadActions(), slotMailDownloadedForAction(), and swapMailLists().
bool Account::writeToMailBox (const QStringList & mail, const QString & box) [protected]
Writes the given mail into the mailbox.
Parameters:
mail the Mail
box path to the mailbox
Returns:
TRUE - Writing was successful
Definition at line 2112 of file account.cpp.
References isMailDir(), and moveCounter.
Referenced by slotMailDownloadedForAction().
bool Account::isMailDir (const QDir & path) [protected]
Returns whether the given directory is a maildir directory.
Parameters:
path the directory for test
Returns:
TRUE - directory is a maildir directory
Definition at line 2178 of file account.cpp.
Referenced by writeToMailBox().
bool Account::isSpam (QStringList mail) const [protected]
Forwards the given mail to SpamAssassin and returns the test result.
Parameters:
mail the mail to test
Returns:
TRUE - mail is spam
Definition at line 2205 of file account.cpp.
References isSpamAssassinRunning().
Referenced by slotMailDownloadedForAction().
bool Account::isSpamAssassinRunning () const [protected]
Looks for a running spamd daemon of SpamAssassin.
Returns:
TRUE - SpamAssassin is running
Definition at line 2242 of file account.cpp.
References NAME_SPAMASSASSIN_DAEMON.
Referenced by isSpam().
void Account::startTLS () [protected]
Invites the server to crypt using TLS (STARTTLS).
Definition at line 2422 of file account.cpp.
References sendCommand(), slotStartTLSResponse(), socket, and POP3Constants::START_TLS().
Referenced by slotAuthMechResponse().
void Account::slotConnected () [protected, virtual, slot]
Connected with signal connected of the socket. Will be invoked after the socket has connected the host.
Definition at line 419 of file account.cpp.
Referenced by Account().
void Account::slotHostFound () [protected, virtual, slot]
Connected with signal hostFound of the socket. Will be invoked after the socket has done the DNS lookup.
Definition at line 423 of file account.cpp.
Referenced by Account().
void Account::slotSocketError (KTcpSocket::Error errorCode) [protected, slot]
Connected with signal error of the socket. Will be invoked, when an socket error occures.
Parameters:
errorCode Error code of the socket
Definition at line 427 of file account.cpp.
References dontHandleError, getHost(), and handleError().
Referenced by Account().
void Account::slotSSLError (const QList< KSslError > & errors) [protected, slot]
Connected with signale sslErrors of the socket.
Will be invoked, when a ssl socket error occures.
Parameters:
errors list of errors
Definition at line 2299 of file account.cpp.
References dontHandleError, finishTask(), getName(), sigMessageWindowClosed(), sigMessageWindowOpened(), and socket.
Referenced by Account().
void Account::slotReadFirstServerMessage () [protected, slot]
Reads the first message send by server.
Definition at line 702 of file account.cpp.
References apopAvail, apopTimestamp, finishTask(), getCapabilities(), getHost(), handleError(), isPositiveServerMessage(), and readfromSocket().
Referenced by doConnect().
void Account::slotCapabilitiesResponse () [protected, slot]
Reads the capabilities from the server.
See also:
getCapabilities()
Definition at line 780 of file account.cpp.
References POP3Constants::CAPA_RESPONSE_STLS(), finishTask(), getAuthMech(), handleError(), isPositiveServerMessage(), readfromSocket(), removeEndOfResponseMarker(), removeStatusIndicator(), supportsStartTLS, transferSecurity, and Types::TransSecTLS.
Referenced by getCapabilities().
void Account::slotAuthMechResponse () [protected, slot]
Connected with the signal readyRead of the socket by getAuthMech(). Analyzes the response and sets the authentication mechanism flags of this account.
See also:
getAuthMech
Definition at line 858 of file account.cpp.
References allowUnsecureLogin, apopAvail, dontUseAPOP, finishTask(), getName(), isPositiveServerMessage(), loginApop(), loginUser(), readfromSocket(), removeEndOfResponseMarker(), removeStatusIndicator(), sigMessageWindowClosed(), sigMessageWindowOpened(), startTLS(), supportsStartTLS, transferSecurity, and Types::TransSecTLS.
Referenced by getAuthMech().
void Account::slotCommitResponse () [protected, slot]
Connected with signal readyRead of the socket by commit(). Analyzes the commit response of the server.
See also:
ccommit()
Definition at line 961 of file account.cpp.
References POP3Constants::COMMIT(), finishTask(), getHost(), handleError(), isPositiveServerMessage(), and readfromSocket().
Referenced by commit().
void Account::slotLoginUserResponse () [protected, slot]
Received the response of the USER command during login.
See also:
loginUser()
Definition at line 994 of file account.cpp.
References finishTask(), handleError(), isPositiveServerMessage(), loginPasswd(), readfromSocket(), and removeStatusIndicator().
Referenced by loginUser().
void Account::slotLoginPasswdResponse () [protected, slot]
Received the response of the PASS command during login.
See also:
loginPasswd()
Definition at line 1028 of file account.cpp.
References Types::AccountDeleting, Types::AccountDownloading, Types::AccountRefreshing, commit(), deleteNextMail(), finishTask(), getState(), getUIDList(), handleError(), isPositiveServerMessage(), readfromSocket(), removeStatusIndicator(), and showNextMail().
Referenced by loginPasswd().
void Account::slotLoginApopResponse () [protected, slot]
Receives the response of a login using APOP.
See also:
loginApop()
Definition at line 1092 of file account.cpp.
References Types::AccountDeleting, Types::AccountDownloading, Types::AccountRefreshing, allowUnsecureLogin, closeConnection(), commit(), deleteNextMail(), doConnect(), dontUseAPOP, finishTask(), getState(), getUIDList(), handleError(), isPositiveServerMessage(), readfromSocket(), removeStatusIndicator(), and showNextMail().
Referenced by loginApop().
void Account::slotUIDListResponse () [protected, slot]
Reiceves the response of the UIDL command, which gets the UID's of the mails.
See also:
getUIDList()
Definition at line 1173 of file account.cpp.
References accountList, MailList::addMail(), finishTask(), getMailSizes(), getName(), handleError(), MailList::hasMail(), MailList::isNew(), isPositiveServerMessage(), AccountList::keepNew(), mails, readfromSocket(), refreshPerformedByFilters, removeEndOfResponseMarker(), removeStatusIndicator(), swapMailLists(), and tempMailList.
Referenced by getUIDList().
void Account::slotMailSizesResponse () [protected, slot]
Receives the response of the LIST command, which gets the numbers and sizes of the mails.
See also:
getMailSizes()
Definition at line 1406 of file account.cpp.
References finishTask(), getHeaders(), getHost(), handleError(), isPositiveServerMessage(), POP3Constants::MAIL_LIST(), readfromSocket(), removeEndOfResponseMarker(), removeStatusIndicator(), MailList::setSize(), and tempMailList.
Referenced by getMailSizes().
void Account::slotGetHeaderResponse () [protected, slot]
Receives the header requested by getNextHeader().
Stores the received headers into the appropriate instance of the mail list. Removes the first mail from newMails and invokes getNextHeader() again to get the next header. If the list is empty after it has removed the first item, it will call copyHeaders().
Definition at line 1540 of file account.cpp.
References copyHeaders(), finishTask(), getHost(), getName(), getNextHeader(), handleError(), isPositiveServerMessage(), newMails, readfromSocket(), removeEndOfResponseMarker(), removeStatusIndicator(), MailList::setHeader(), and tempMailList.
Referenced by getNextHeader().
void Account::slotMailDeleted () [protected, slot]
Removes the deleted mail from the internal mail list (m_pshowrecord).
Removes the first mail from MailsToDelete and invokes deleteNextMail() again to delete the next mail. If the list is empty after it has removed the first item, it will call commitDelete().
See also:
deleteNextMail()
MailsToDelete
Definition at line 1702 of file account.cpp.
References applyFiltersDeleted(), commit(), deleteNextMail(), deletionPerformedByFilters, finishTask(), getHost(), getName(), handleError(), isPositiveServerMessage(), mailsToDelete, and readfromSocket().
Referenced by deleteNextMail().
void Account::slotBodyDownloaded () [protected, slot]
Opens a window (class ShowMailDialog) with the downloaded mail body.
Removes the first mail from MailsToShow and invokes showNextMail() again to show the next mail. If the list is empty after it has removed the first item, it will call commitDownloading().
See also:
showNextMail()
MailsToShow
ShowMailDialog
Definition at line 1745 of file account.cpp.
References commit(), CONFIG_ENTRY_VIEW_USE_HTML, CONFIG_GROUP_VIEW, MailList::decodeMailBody(), DEFAULT_VIEW_USE_HTML, finishTask(), MailList::getDateOf(), getHost(), getName(), MailList::getSenderOf(), MailList::getSizeOf(), MailList::getSubjectOf(), handleError(), isPositiveServerMessage(), mails, mailsToShow, readfromSocket(), removeEndOfResponseMarker(), removeStatusIndicator(), showNextMail(), sigMessageWindowClosed(), sigMessageWindowOpened(), timeOutTime, and timeoutTimer.
Referenced by showNextMail().
void Account::slotMailDownloadedForAction () [protected, slot]
Downloads a mail to write it into a mailbox or do a spam check.
Maybe it puts the number of the downloaded mail into the list of mails to delete (mailsToDelete). Removes the first mail from MailsToMove and invokes getNextMailForMove() again to get and write the next mail. If the list is empty after it has removed the first item, it will call applyFilters() to continue the filtering. If an error is occurred the current mail will not put into MailsToDelete. And it returns to applyFilters() immediately.
See also:
MailsToDownload
getNextMailForDownloadActions()
applyFilters()
Definition at line 1886 of file account.cpp.
References applyFilters(), Types::FActDelete, Types::FActMark, Types::FActMove, Types::FActSpamcheck, finishTask(), fLog, getHost(), getName(), getNextMailForDownloadActions(), handleError(), isPositiveServerMessage(), isSpam(), mails, mailsToDelete, mailsToDownload, mailsToShow, nmbDeletedMailsLastRefresh, nmbDeletedMailsLastStart, nmbMovedMailsLastRefresh, nmbMovedMailsLastStart, readfromSocket(), removeEndOfResponseMarker(), removeStatusIndicator(), MailList::setMarkAtNextViewRefresh(), spamAction, spamMailbox, MailList::writeToDeleteLog(), writeToMailBox(), and MailList::writeToMoveLog().
Referenced by getNextMailForDownloadActions().
void Account::slotCommitBeforeRefreshDone () [protected, slot]
Restarts a second refresh cycle after a deletion performed by the filter.
See also:
commitBeforeRefresh
applyFiltersDeleted
Definition at line 2066 of file account.cpp.
References refreshMailList().
Referenced by commitBeforeRefresh().
void Account::slotTimeout () [protected, slot]
Connected with the timeout timer.
Closes the server connect and finishes the task
See also:
timeoutTimer
Definition at line 2408 of file account.cpp.
References handleError().
Referenced by Account().
void Account::slotStartTLSResponse () [protected, slot]
Receives the response of the STLS command.
Definition at line 2433 of file account.cpp.
References allowUnsecureLogin, apopAvail, dontUseAPOP, finishTask(), getHost(), getName(), isPositiveServerMessage(), loginApop(), loginUser(), readfromSocket(), sigMessageWindowClosed(), sigMessageWindowOpened(), and socket.
Referenced by startTLS().
void Account::sigDeleteReady (QString account) [signal]
Will be emitted when all selected mails are deleted.
Parameters:
account name of the account, which has emitted this signal
Referenced by deleteMails(), finishTask(), and handleError().
void Account::sigShowBodiesReady (QString account) [signal]
Will be emitted when the bodies of all selected mails are downloaded and shown.
Parameters:
account name of the account, which has emitted this signal
Referenced by finishTask(), handleError(), and showMails().
void Account::sigConfigChanged () [signal]
Will be emitted when the settings have been changed.
Referenced by assertPassword().
void Account::sigMessageWindowOpened () [signal]
Will be emitted, when a window to show a message was opened.
Referenced by handleError(), slotAuthMechResponse(), slotBodyDownloaded(), slotSSLError(), and slotStartTLSResponse().
void Account::sigMessageWindowClosed () [signal]
Will be emitted, when a window to show a message was closed.
Referenced by handleError(), slotAuthMechResponse(), slotBodyDownloaded(), slotSSLError(), and slotStartTLSResponse().
void Account::sigRefreshReady (QString account) [signal]
Will be emitted, when the mail list was refreshed.
Parameters:
account name of the account, which has emitted this signal
Referenced by finishTask(), handleError(), and refreshMailList().
Member Data Documentation
QString Account::name [private]
Name of this account.
Definition at line 929 of file account.h.
Referenced by deleteMails(), getName(), refreshMailList(), and showMails().
bool Account::active [private]
TRUE - account is active; FALSE - account is not active.
Definition at line 934 of file account.h.
Referenced by init(), isActive(), and load().
TransferSecurity_Type Account::transferSecurity [private]
Type of the transfer security.
Definition at line 939 of file account.h.
Referenced by doConnect(), load(), readfromSocket(), slotAuthMechResponse(), and slotCapabilitiesResponse().
KUrl Account::url [private]
Uniform Resource Locator of the account on the mail server.
Definition at line 944 of file account.h.
Referenced by assertPassword(), getHost(), getPassword(), getPort(), getProtocol(), getUser(), hasPassword(), print(), setHost(), setPassword(), setPort(), setProtocol(), and setUser().
int Account::passwordStorage [private]
Type of password storage.
valid values are: CONFIG_VALUE_ACCOUNT_PASSWORD_DONT_SAVE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_FILE, CONFIG_VALUE_ACCOUNT_PASSWORD_SAVE_KWALLET The Constants are defined in constants.h
See also:
getPasswordStorage()
setPasswordStorage()
Definition at line 954 of file account.h.
Referenced by assertPassword(), getPasswordStorage(), load(), and setPasswordStorage().
MailList* Account::mails [private]
The mail container.
Definition at line 959 of file account.h.
Referenced by Account(), applyFilters(), copyHeaders(), getAllMails(), getNumberMails(), getNumberNewMails(), getTotalSize(), print(), readStoredMails(), saveOptions(), slotBodyDownloaded(), slotMailDownloadedForAction(), slotUIDListResponse(), swapMailLists(), and ~Account().
MailList* Account::tempMailList [private]
While refreshing, this mail list instance will be used to build a new mail list. After that this pointer will be assigned to maillist.
Definition at line 966 of file account.h.
Referenced by copyHeaders(), getHeaders(), refreshMailList(), slotGetHeaderResponse(), slotMailSizesResponse(), slotUIDListResponse(), and swapMailLists().
KTcpSocket* Account::socket [private]
The socket. Handles all server operations.
Definition at line 972 of file account.h.
Referenced by Account(), cancelTask(), closeConnection(), commit(), commitBeforeRefresh(), deleteNextMail(), doConnect(), getAuthMech(), getCapabilities(), getMailSizes(), getNextHeader(), getNextMailForDownloadActions(), getUIDList(), loginApop(), loginPasswd(), loginUser(), readfromSocket(), sendCommand(), showNextMail(), slotSSLError(), slotStartTLSResponse(), and startTLS().
AccountList* Account::accountList [private]
Pointer to the account list object.
Definition at line 977 of file account.h.
Referenced by slotUIDListResponse().
bool Account::quitSent [private]
TRUE - the QUIT command was sent to the server. Normally set by the commit methode.
Inititates by initBeforeConnect()
See also:
initBeforeConnect()
Definition at line 985 of file account.h.
Referenced by commit(), commitBeforeRefresh(), and initBeforeConnect().
QTimer* Account::timeoutTimer [private]
This timer kills a running operation after the preset time.
Definition at line 990 of file account.h.
Referenced by Account(), finishTask(), handleError(), initBeforeConnect(), and slotBodyDownloaded().
Types::AccountState_Type Account::state [private]
State of the account.
Definition at line 995 of file account.h.
Referenced by cancelTask(), deleteMails(), finishTask(), getState(), handleError(), init(), refreshMailList(), and showMails().
bool Account::apopAvail [private]
APOP available.
Definition at line 1000 of file account.h.
Referenced by initBeforeConnect(), slotAuthMechResponse(), slotReadFirstServerMessage(), and slotStartTLSResponse().
bool Account::dontUseAPOP [private]
Is set to TRUE by slotLoginAPOPResponse if the first login with APOP is failed.
After a setup load it will set to false.
Definition at line 1007 of file account.h.
Referenced by initBeforeConnect(), slotAuthMechResponse(), slotLoginApopResponse(), and slotStartTLSResponse().
QString Account::apopTimestamp [private]
Timestamp for APOP sent with the server greeting.
Definition at line 1012 of file account.h.
Referenced by loginApop(), and slotReadFirstServerMessage().
bool Account::allowUnsecureLogin [private]
TRUE - unsafe login is allowed if a secure login failed.
Definition at line 1017 of file account.h.
Referenced by isUnsecureLoginAllowed(), load(), slotAuthMechResponse(), slotLoginApopResponse(), and slotStartTLSResponse().
bool Account::filterApplied [private]
This is a flag whether the filters was applied during a refresh cycle.
If some mails was deleted (recommend by the filter), we need a actual list of mails from the server. Therefore a second refresh cycle will be started. To avoid a never-ending loop this flag will be set to TRUE by applyFilters(). If the second refresh is running this one will not invoke the filters.
Definition at line 1027 of file account.h.
Referenced by applyFilters(), init(), initBeforeConnect(), and swapMailLists().
bool Account::refreshPerformedByFilters [private]
This flag is set by applyFiltersDeleted() to indicate the refresh cycle is the second one after a deletion which was performed by filters.
The refresh cycle need it to hold the remaining mails as new.
Definition at line 1034 of file account.h.
Referenced by applyFiltersDeleted(), refreshMailList(), slotUIDListResponse(), and swapMailLists().
MailNumberList_Type Account::newMails [private]
Contains the numbers of new mails.
Set by getHeaders() and used by getNextHeader() to download the headers of the new mails.
See also:
getHeaders()
getNextHeader()
Definition at line 1044 of file account.h.
Referenced by getHeaders(), getNextHeader(), and slotGetHeaderResponse().
MailNumberList_Type Account::mailsToDelete [private]
Contains the numbers of mails which will be deleted.
Set by addMailToDelete() and used by deleteNextMail() to get the number of the next mail to delete.
See also:
addMailToDelete()
deleteNextMail()
Definition at line 1054 of file account.h.
Referenced by addMailToDelete(), applyFilters(), deleteMails(), deleteNextMail(), finishTask(), handleError(), slotMailDeleted(), and slotMailDownloadedForAction().
MailToDownloadMap_Type Account::mailsToDownload [private]
Contains the numbers of the mails shall be moved for actions like moving to mailbox or spam check.
Contains also some parameters (like mailbox) about the action which have to be performed. Set and used by applyFilters().
See also:
applyFilters()
Definition at line 1063 of file account.h.
Referenced by applyFilters(), finishTask(), getNextMailForDownloadActions(), handleError(), and slotMailDownloadedForAction().
MailNumberList_Type Account::mailsToShow [private]
Contains the numbers of mails for which the bodies will be shown.
Set by showSelectedMails() and used by showNextMail() to get the number of the next mail to show.
See also:
showSelectedMails()
showNextMail()
Definition at line 1073 of file account.h.
Referenced by addMailToShow(), finishTask(), handleError(), showMails(), showNextMail(), slotBodyDownloaded(), and slotMailDownloadedForAction().
FilterLog* Account::fLog [private]
Pointer to the filter log.
Will be set by refreshMailList() at every refresh.
Definition at line 1080 of file account.h.
Referenced by applyFilters(), refreshMailList(), and slotMailDownloadedForAction().
int Account::nmbDeletedMailsLastRefresh [private]
Number of deleted mails by last refresh.
Definition at line 1085 of file account.h.
Referenced by applyFilters(), init(), numberDeletedMailsLastRefresh(), refreshMailList(), and slotMailDownloadedForAction().
int Account::nmbMovedMailsLastRefresh [private]
Number of moved mails by last refresh.
Definition at line 1090 of file account.h.
Referenced by init(), numberMovedMailsLastRefresh(), refreshMailList(), and slotMailDownloadedForAction().
int Account::nmbMovedMailsLastStart [private]
Number of moved mails since start.
Definition at line 1095 of file account.h.
Referenced by init(), numberMovedMailsStart(), and slotMailDownloadedForAction().
int Account::nmbIgnoredMails [private]
Number of ignored mails by last refresh.
Definition at line 1100 of file account.h.
Referenced by applyFilters(), init(), numberIgnoredMails(), and refreshMailList().
int Account::moveCounter [private]
Counter for moving to create an unique file name.
Definition at line 1105 of file account.h.
Referenced by init(), and writeToMailBox().
int Account::nmbDeletedMailsLastStart [private]
Number of deleted mails since start.
Definition at line 1110 of file account.h.
Referenced by applyFilters(), init(), numberDeletedMailsStart(), and slotMailDownloadedForAction().
bool Account::downloadActionsInvoked [private]
This flag is set to TRUE by applyFilters() to indicate the mailbodies are downloading and writing to the mailboxes or spam checking.
When this is ended, applyFilters() will be called again and it reset this flag
Definition at line 1117 of file account.h.
Referenced by applyFilters(), init(), and initBeforeConnect().
HeaderFilter Account::headerFilter [private]
Every account has is own header filter instance.
Definition at line 1122 of file account.h.
Referenced by applyFilters(), reloadFilterSettings(), and swapMailLists().
bool Account::deletionPerformedByFilters [private]
This flag is set by applyFilters() to indicate the deletion cycle is performed by filters and not by user.
The deletion methodes need it to decide on branch targets
Definition at line 1129 of file account.h.
Referenced by applyFilters(), applyFiltersDeleted(), deleteNextMail(), init(), initBeforeConnect(), and slotMailDeleted().
QString Account::spamMailbox [private]
Mailbox for Spam, if configured.
Definition at line 1134 of file account.h.
Referenced by load(), and slotMailDownloadedForAction().
FilterAction_Type Account::spamAction [private]
Action which shall be done, if the mail is Spam.
Definition at line 1139 of file account.h.
Referenced by load(), and slotMailDownloadedForAction().
bool Account::dontHandleError [private]
TRUE - the error will not be handled by slotSocketError.
Definition at line 1144 of file account.h.
Referenced by init(), initBeforeConnect(), readfromSocket(), slotSocketError(), and slotSSLError().
bool Account::informAboutErrors [private]
TRUE - informs the user about connection errors.
FALSE - doesn't inform
Definition at line 1151 of file account.h.
Referenced by handleError(), and load().
int Account::timeOutTime [private]
Seconds to Timeout.
Definition at line 1156 of file account.h.
Referenced by initBeforeConnect(), load(), and slotBodyDownloaded().
bool Account::supportsStartTLS [private]
TRUE - the server supports StartTLS.
Set by slotCapabilitiesResponse()
See also:
slotCapabilitiesResponse
Definition at line 1164 of file account.h.
Referenced by initBeforeConnect(), slotAuthMechResponse(), and slotCapabilitiesResponse().
The documentation for this class was generated from the following files:
src/account.h
src/account.cpp