KShowmail: Mail Class Reference
Mail Class Reference
This class represents a mail.
#include <mail.h>
Public Member Functions
Mail (long number, const QString &unid, bool isNew, QPointer< Account > account, QObject *parent)
Mail (const Mail &mail)
~Mail ()
Mail & operator= (const Mail &other)
void setSize (long size)
void setNumber (int number)
void print () const
QString getSubject () const
QString getUNID () const
long getSize () const
int getNumber () const
void setNew (bool isnew)
bool isNew () const
void setHeader (const QStringList &header)
QStringList getHeader () const
void setSubject (const QString &subject)
void setFrom (const QString &from)
void setTo (const QString &to)
void setDate (const QString &date)
KDateTime getDateTime () const
void setContent (const QString &content)
QString getContent () const
QPointer< Account > getAccount () const
QString getFrom () const
QString getTo () const
QString getSizeSuffix () const
FilterAction_Type applyHeaderFilter (HeaderFilter *filter, QString account, QString &mailbox, FilterLog *log=NULL)
void save (QDomDocument &doc, QDomElement &parent)
bool isMarkedByFilter () const
QStringList decodeMailBody (const QStringList &body, bool preferHTML) const
QString getBoundary () const
QString getCharsetFromHeader () const
QString getTransferEncodingFromHeader () const
void writeToMoveLog (FilterLog *log, QString account, QString mailbox)
void writeToDeleteLog (FilterLog *log, QString account)
void setMarkAtNextViewRefresh ()
int compare (const Mail &other, MailSort_Type property)
QString getAccountName () const
Protected Member Functions
void init ()
QString scanHeader (const QString &item) const
QString scanBodyPart (const QStringList &part, const QString &item) const
QString decodeRfc2047 (const QString &text) const
QString getCharset (const QStringList &text) const
QString getTransferEncoding (const QStringList &text) const
Private Attributes
QString unid
QString subject
QStringList header
long size
int number
bool _new
QString from
QString to
KDateTime sendDate
QString contentType
bool markedByFilter
QPointer< Account > acc
QString accountName
Detailed Description
This class represents a mail.
Definition at line 51 of file mail.h.
Constructor & Destructor Documentation
Mail::Mail (long number, const QString & unid, bool isNew, QPointer< Account > account, QObject * parent)
Constructor
Parameters:
number number of the mail on the server
unid Unique ID of the mail
isNew TRUE - mail is new; FALSE - mail is not new
account pointer to the parent account
parent parent object
Definition at line 20 of file mail.cpp.
References acc, accountName, init(), setNew(), and setNumber().
Mail::Mail (const Mail & mail)
Copy Constructor
Parameters:
mail source mail
Definition at line 33 of file mail.cpp.
Mail::~Mail ()
Destructor
Definition at line 41 of file mail.cpp.
Member Function Documentation
Mail & Mail::operator= (const Mail & other)
Assign operator
Parameters:
other other mail
Definition at line 852 of file mail.cpp.
References _new, acc, accountName, contentType, from, header, markedByFilter, number, sendDate, size, subject, to, and unid.
void Mail::setSize (long size)
Sets the size
Parameters:
size mail size (Bytes)
Definition at line 45 of file mail.cpp.
Referenced by MailList::readStoredMails(), and MailList::setSize().
void Mail::setNumber (int number)
Sets the number.
Parameters:
number the number
Definition at line 83 of file mail.cpp.
Referenced by Mail().
void Mail::print () const
Prints the data of this mail to stdout
Definition at line 50 of file mail.cpp.
References contentType, from, getNumber(), getSize(), getSubject(), getUNID(), isNew(), sendDate, and to.
Referenced by MailList::print().
QString Mail::getSubject () const
Returns the subject
Returns:
subject
Definition at line 63 of file mail.cpp.
References subject.
Referenced by applyHeaderFilter(), compare(), MailViewModel::data(), MailViewModel::getSelectedSubjects(), MailList::getSubjectOf(), print(), KShowmail::slotShowHeader(), writeToDeleteLog(), and writeToMoveLog().
QString Mail::getUNID () const
Returns the UNID.
Returns:
UNID
Definition at line 68 of file mail.cpp.
References unid.
Referenced by MailList::getHeaderOf(), MailList::getUIDsOfOldMails(), MailList::hasMail(), MailList::isNew(), print(), save(), and MailList::setHeader().
long Mail::getSize () const
Returns the size of this mail
Returns:
mail size (Bytes)
Definition at line 73 of file mail.cpp.
References size.
Referenced by applyHeaderFilter(), compare(), MailList::getTotalSize(), print(), and save().
int Mail::getNumber () const
Returns the number of this mail on the server
Returns:
number
Definition at line 78 of file mail.cpp.
References number.
Referenced by MailList::applyHeaderFilter(), compare(), MailViewModel::data(), MailList::decodeMailBody(), MailList::getCharsetFromHeaderOf(), MailList::getDateOf(), MailList::getNewMails(), MailList::getSenderOf(), MailList::getSizeOf(), MailList::getSubjectOf(), print(), MailList::removeMail(), save(), MailList::setHeader(), MailList::setMarkAtNextViewRefresh(), MailList::setSize(), KShowmail::slotDelete(), KShowmail::slotShowMessage(), MailList::writeToDeleteLog(), and MailList::writeToMoveLog().
void Mail::setNew (bool isnew)
Sets whether the mail is new or not.
Parameters:
isnew TRUE - mail is new; FALSE - mail is not new
Definition at line 94 of file mail.cpp.
References _new.
Referenced by Mail().
bool Mail::isNew () const
Returns whether the mail is new or not.
Returns:
TRUE - mail is new
FALSE - mail is not new
Definition at line 99 of file mail.cpp.
References _new.
Referenced by compare(), MailViewModel::data(), MailList::getNewMails(), MailList::getNumberNewMails(), MailList::getUIDsOfOldMails(), MailList::isNew(), and print().
void Mail::setHeader (const QStringList & header)
Sets the mail header and extracts From, To, Subject, Date and Content Type. All parts of the header are coded according RFC 2047.
Parameters:
header the mail header
Definition at line 104 of file mail.cpp.
References from, scanHeader(), setContent(), setDate(), setFrom(), setSubject(), setTo(), subject, and to.
Referenced by MailList::readStoredMails(), and MailList::setHeader().
QStringList Mail::getHeader () const
Returns the header
Returns:
mail header
Definition at line 219 of file mail.cpp.
References header.
Referenced by applyHeaderFilter(), MailList::getHeaderOf(), save(), scanHeader(), and KShowmail::slotShowHeader().
void Mail::setSubject (const QString & subject)
Sets the given string as subject
Parameters:
subject the mail subject
Definition at line 192 of file mail.cpp.
References decodeRfc2047().
Referenced by setHeader().
void Mail::setFrom (const QString & from)
Sets the given string as sender address
Parameters:
from sender address
Definition at line 197 of file mail.cpp.
Referenced by setHeader().
void Mail::setTo (const QString & to)
Sets the given string as recipient address
Parameters:
to recipient address
Definition at line 202 of file mail.cpp.
Referenced by setHeader().
void Mail::setDate (const QString & date)
Converts the given string to a date-time value and stores it.
Parameters:
date the date
Definition at line 207 of file mail.cpp.
References sendDate.
Referenced by setHeader().
KDateTime Mail::getDateTime () const
Returns the datetime of mail send
Definition at line 393 of file mail.cpp.
References sendDate.
Referenced by applyHeaderFilter(), compare(), MailViewModel::data(), MailList::getDateOf(), writeToDeleteLog(), and writeToMoveLog().
void Mail::setContent (const QString & content)
Sets the given string as content type.
Parameters:
content the content type
Definition at line 214 of file mail.cpp.
Referenced by setHeader().
QString Mail::getContent () const
Returns the content type.
Returns:
content type
Definition at line 398 of file mail.cpp.
References contentType.
Referenced by compare(), and MailViewModel::data().
QPointer< Account > Mail::getAccount () const
Returns a pointer to the account which contains this mail.
Returns:
account
Definition at line 357 of file mail.cpp.
References acc.
Referenced by KShowmail::slotDelete(), and KShowmail::slotShowMessage().
QString Mail::getFrom () const
Returns the sender address.
Returns:
sender address
Definition at line 362 of file mail.cpp.
References from.
Referenced by applyHeaderFilter(), compare(), MailViewModel::data(), MailViewModel::getSelectedSenders(), MailList::getSenderOf(), writeToDeleteLog(), and writeToMoveLog().
QString Mail::getTo () const
Returns the addressee.
Returns:
the addressee
Definition at line 367 of file mail.cpp.
References to.
Referenced by applyHeaderFilter(), compare(), and MailViewModel::data().
QString Mail::getSizeSuffix () const
Returns the mails size as string with suffix
Definition at line 372 of file mail.cpp.
References size.
Referenced by MailViewModel::data(), and MailList::getSizeOf().
FilterAction_Type Mail::applyHeaderFilter (HeaderFilter * filter, QString account, QString & mailbox, FilterLog * log = NULL)
Looks for a filter matching the mail header and returns the action recommend by this filter. If the action is MARK, it set markAtViewRefresh to True so the related view entry will be marked at the next view refresh.
Parameters:
filter pointer to the header filter
account name of the account
mailbox reference to a QString object in which the mailbox name shall be written if the action is MOVE
log pointer to the filter log
Returns:
recommend action
See also:
FilterAction_Type
HeaderFilter
markAtViewRefresh
Definition at line 403 of file mail.cpp.
References FilterLog::addDeletedMail(), FilterLog::addMovedMail(), HeaderFilter::check(), Types::FActDelete, Types::FActMark, Types::FActMove, getDateTime(), getFrom(), getHeader(), getSize(), getSubject(), getTo(), and markedByFilter.
Referenced by MailList::applyHeaderFilter().
void Mail::save (QDomDocument & doc, QDomElement & parent)
Creates a new DOM element in the given DOM document and add it to given DOM parent element
Parameters:
doc the DOM document in that all options are stored
parent the parent element (account) of the mail
Definition at line 422 of file mail.cpp.
References ATTRIBUTE_MAIL_NUMBER, ATTRIBUTE_MAIL_SIZE, ATTRIBUTE_MAIL_UID, getHeader(), getNumber(), getSize(), getUNID(), HEADER_SEPARATOR, ITEM_MAIL_HEADER, and ITEM_MESSAGE.
Referenced by MailList::saveMails().
bool Mail::isMarkedByFilter () const
Returns whether this mail was marked by filter.
Returns:
TRUE - marked; FALSE - not marked
Definition at line 446 of file mail.cpp.
References markedByFilter.
Referenced by MailViewModel::getMarkedMails().
QStringList Mail::decodeMailBody (const QStringList & body, bool preferHTML) const
Decodes the given mail body. The mail object has to do this job, because it has stored the mail header and therefore it knows the content type and encoding of the mail. It decodes just the text or html part of the body. The rest of it will be rejected.
Parameters:
body the encoded mail (including header)
preferHTML decode HTML part if present
Returns:
decoded mail body
Definition at line 451 of file mail.cpp.
References getBoundary(), getCharset(), getCharsetFromHeader(), getTransferEncoding(), and getTransferEncodingFromHeader().
Referenced by MailList::decodeMailBody().
QString Mail::getBoundary () const
Returns the boundary, if the mail has a multi part body. Otherwise it returns an empty string.
Returns:
boundary
Definition at line 661 of file mail.cpp.
References contentType, and header.
Referenced by decodeMailBody().
QString Mail::getCharsetFromHeader () const
Returns the char set of the content (e.g. iso-8859-1) from the header. If no char set is denoted, it will returns an empty string.
Returns:
charset
Definition at line 697 of file mail.cpp.
References getCharset(), and header.
Referenced by decodeMailBody(), and MailList::getCharsetFromHeaderOf().
QString Mail::getTransferEncodingFromHeader () const
Returns the transfer encoding string from the header if existing. Otherwise it returns an empty string.
Returns:
transfer encoding
Definition at line 745 of file mail.cpp.
References scanHeader().
Referenced by decodeMailBody().
void Mail::writeToMoveLog (FilterLog * log, QString account, QString mailbox)
Writes this mail into the Move Log.
Parameters:
log pointer to the log
account name of the account
mailbox name of the mailbox
Definition at line 757 of file mail.cpp.
References FilterLog::addMovedMail(), getDateTime(), getFrom(), and getSubject().
Referenced by MailList::writeToMoveLog().
void Mail::writeToDeleteLog (FilterLog * log, QString account)
Writes this mail into the Delete Log.
Parameters:
log pointer to the log
account name of the account
Definition at line 767 of file mail.cpp.
References FilterLog::addDeletedMail(), getDateTime(), getFrom(), and getSubject().
Referenced by MailList::writeToDeleteLog().
void Mail::setMarkAtNextViewRefresh ()
The mail will be marked at the next view refresh.
Definition at line 762 of file mail.cpp.
References markedByFilter.
Referenced by MailList::setMarkAtNextViewRefresh().
int Mail::compare (const Mail & other, MailSort_Type property)
Compares this mail with other and returns an integer less than, equal to, or greater than zero if this mail is less than, equal to, or greater than other.
Parameters:
other other mail
property the mail property which will be compared
Definition at line 772 of file mail.cpp.
References getAccountName(), getContent(), getDateTime(), getFrom(), getNumber(), getSize(), getSubject(), getTo(), isNew(), Types::MailSortAccount, Types::MailSortContent, Types::MailSortDate, Types::MailSortFrom, Types::MailSortNumber, Types::MailSortSize, Types::MailSortState, Types::MailSortSubject, and Types::MailSortTo.
Referenced by MailViewModel::sort().
QString Mail::getAccountName () const
Returns the name of the parent account.
Returns:
name of the parent account
See also:
accountName
Definition at line 847 of file mail.cpp.
References accountName.
Referenced by compare(), MailViewModel::data(), and KShowmail::slotShowHeader().
void Mail::init () [protected]
Initiates the object
Definition at line 88 of file mail.cpp.
References markedByFilter, and size.
Referenced by Mail().
QString Mail::scanHeader (const QString & item) const [protected]
Searches in the header for a line which starts with the given item. For example: scanHeader("From") will find the line "From: Ulrich Weigelt <ulrich.weigelt@gmx.de>" and returns "Ulrich Weigelt <ulrich.weigelt@gmx.de>" Returns an empty string (""), if nothing was found.
Parameters:
item the search item
Returns:
the content of the found line
Definition at line 143 of file mail.cpp.
References getHeader(), and header.
Referenced by getTransferEncodingFromHeader(), and setHeader().
QString Mail::scanBodyPart (const QStringList & part, const QString & item) const [protected]
Searches in the given body part for a line which starts with the given item. For example: scanBodyPart("Content-Transfer-Encoding") will find the line "Content-Transfer-Encoding: 7bit" and returns "7bit" Returns an empty string (""), if nothing was found.
Parameters:
part the body part
item the search item
Returns:
the content of the found line
Definition at line 167 of file mail.cpp.
Referenced by getTransferEncoding().
QString Mail::decodeRfc2047 (const QString & text) const [protected]
Decodes a rfc2047 encoded string
Definition at line 224 of file mail.cpp.
Referenced by setSubject().
QString Mail::getCharset (const QStringList & text) const [protected]
Returns the charset of the given header or body part.
It looks for the charset tag and returns the string behind this.
Parameters:
text body part or header
Returns:
charset string
Definition at line 702 of file mail.cpp.
Referenced by decodeMailBody(), and getCharsetFromHeader().
QString Mail::getTransferEncoding (const QStringList & text) const [protected]
Returns the transfer encoding of the given header or body part.
It looks for the transfer encoding tag and returns the string behind this.
Parameters:
text body part or header
Returns:
charset string
Definition at line 750 of file mail.cpp.
References scanBodyPart().
Referenced by decodeMailBody().
Member Data Documentation
QString Mail::unid [private]
UNID of this mail
Definition at line 322 of file mail.h.
Referenced by getUNID(), and operator=().
QString Mail::subject [private]
Subject
Definition at line 327 of file mail.h.
Referenced by getSubject(), operator=(), and setHeader().
QStringList Mail::header [private]
Header
Definition at line 332 of file mail.h.
Referenced by getBoundary(), getCharsetFromHeader(), getHeader(), operator=(), and scanHeader().
long Mail::size [private]
Size (Bytes)
Definition at line 337 of file mail.h.
Referenced by getSize(), getSizeSuffix(), init(), and operator=().
int Mail::number [private]
Number of this mail on the server
Definition at line 342 of file mail.h.
Referenced by getNumber(), and operator=().
bool Mail::_new [private]
It is set to TRUE when the mail is new.
Definition at line 347 of file mail.h.
Referenced by isNew(), operator=(), and setNew().
QString Mail::from [private]
The sender address
Definition at line 352 of file mail.h.
Referenced by getFrom(), operator=(), print(), and setHeader().
QString Mail::to [private]
The addressee
Definition at line 357 of file mail.h.
Referenced by getTo(), operator=(), print(), and setHeader().
KDateTime Mail::sendDate [private]
The date on which the mail was sent
Definition at line 362 of file mail.h.
Referenced by getDateTime(), operator=(), print(), and setDate().
QString Mail::contentType [private]
The content type
Definition at line 367 of file mail.h.
Referenced by getBoundary(), getContent(), operator=(), and print().
bool Mail::markedByFilter [private]
TRUE - the mail was marked by the filter. It will be set to True by applyHeaderFilter() if the recommend filter action is MARK.
Definition at line 373 of file mail.h.
Referenced by applyHeaderFilter(), init(), isMarkedByFilter(), operator=(), and setMarkAtNextViewRefresh().
QPointer<Account> Mail::acc [private]
Pointer to the parent account
Definition at line 378 of file mail.h.
Referenced by getAccount(), Mail(), and operator=().
QString Mail::accountName [private]
Name of the parent account
Definition at line 383 of file mail.h.
Referenced by getAccountName(), Mail(), and operator=().
The documentation for this class was generated from the following files:
src/mail.h
src/mail.cpp