KShowmail: FilterSetupItem Class Reference
FilterSetupItem Class Reference
This class is used in ConfigFilter to show the available filters in the list view and to store a filter setup.
#include <filtersetupitem.h>
Public Types
enum Column { ColNumber = 0, ColName = 1, ColAction = 2 }
Public Member Functions
FilterSetupItem (QTreeWidget *parent)
FilterSetupItem (QTreeWidget *parent, uint num)
~FilterSetupItem ()
void setName (QString name)
QString getName () const
void setNumber (uint number)
uint getNumber () const
void setAction (int action)
int getAction () const
void setMailBox (QString mailbox)
QString getMailBox () const
void setCriteriaLinkage (int linkage)
int getCriteriaLinkage () const
void setCriteriaList (FilterCriteriaList_Type list)
FilterCriteriaList_Type getCriteriaList () const
void save ()
virtual int compare (FilterSetupItem *i, int col, bool ascending) const
void load ()
Protected Member Functions
void init ()
void updateActionColumn ()
Private Attributes
QString name
KSharedConfigPtr config
FilterCriteriaList_Type criteriaList
int action
QString mailbox
uint number
int linkage
Detailed Description
This class is used in ConfigFilter to show the available filters in the list view and to store a filter setup.
Author:
Ulrich Weigelt <ulrich.weigelt@gmx.de>
Definition at line 41 of file filtersetupitem.h.
Member Enumeration Documentation
enum FilterSetupItem::Column
Column Numbers.
Enumerator:
ColNumber
ColName
ColAction
Definition at line 49 of file filtersetupitem.h.
Constructor & Destructor Documentation
FilterSetupItem::FilterSetupItem (QTreeWidget * parent)
General Constructor
Parameters:
parent the list view
Definition at line 20 of file filtersetupitem.cpp.
References init(), and number.
FilterSetupItem::FilterSetupItem (QTreeWidget * parent, uint num)
Constructor
Parameters:
parent the list view
num filter number
Definition at line 29 of file filtersetupitem.cpp.
References init(), and number.
FilterSetupItem::~FilterSetupItem ()
Destructor
Definition at line 38 of file filtersetupitem.cpp.
Member Function Documentation
void FilterSetupItem::setName (QString name)
Sets the filter name.
Parameters:
name filter name
See also:
name
getName
Definition at line 56 of file filtersetupitem.cpp.
References ColName.
Referenced by init(), load(), and FilterSetupDialog::slotButtonClicked().
QString FilterSetupItem::getName () const
Returns the name of this filter.
Returns:
filter name
See also:
name
setName
Definition at line 64 of file filtersetupitem.cpp.
References name.
Referenced by FilterSetupDialog::fillDialog(), and FilterSetupDialog::FilterSetupDialog().
void FilterSetupItem::setNumber (uint number)
Sets the filter number.
Parameters:
number filter number.
See also:
number
getNumber
Definition at line 69 of file filtersetupitem.cpp.
References ColNumber.
Referenced by ConfigFilter::slotMoveBottom(), ConfigFilter::slotMoveDown(), ConfigFilter::slotMoveTop(), and ConfigFilter::slotMoveUp().
uint FilterSetupItem::getNumber () const
Returns the filter number.
Returns:
filter number
See also:
number
setNumber
Definition at line 236 of file filtersetupitem.cpp.
References number.
Referenced by ConfigFilter::slotMoveBottom(), ConfigFilter::slotMoveDown(), ConfigFilter::slotMoveTop(), ConfigFilter::slotMoveUp(), and ConfigFilter::slotRemove().
void FilterSetupItem::setAction (int action)
Sets the action. See constants.h for valid values (CONFIG_VALUE_FILTER_ACTION...).
Parameters:
action
See also:
getAction
action
Definition at line 77 of file filtersetupitem.cpp.
References CONFIG_VALUE_FILTER_ACTION_DELETE, CONFIG_VALUE_FILTER_ACTION_IGNORE, CONFIG_VALUE_FILTER_ACTION_MARK, CONFIG_VALUE_FILTER_ACTION_MOVE, CONFIG_VALUE_FILTER_ACTION_PASS, CONFIG_VALUE_FILTER_ACTION_SPAMCHECK, DEFAULT_FILTER_ACTION, and updateActionColumn().
Referenced by init(), load(), and FilterSetupDialog::slotButtonClicked().
int FilterSetupItem::getAction () const
Returns the action of this filter. See constants.h for possible values (CONFIG_VALUE_FILTER_ACTION...).
Returns:
action code
See also:
setAction
action
Definition at line 218 of file filtersetupitem.cpp.
References action.
Referenced by FilterSetupDialog::fillDialog().
void FilterSetupItem::setMailBox (QString mailbox)
Sets the mailbox of a move action.
Parameters:
mailbox name of the mailbox
See also:
setMailBox
mailbox
Definition at line 205 of file filtersetupitem.cpp.
References updateActionColumn().
Referenced by load(), and FilterSetupDialog::slotButtonClicked().
QString FilterSetupItem::getMailBox () const
Returns the mailbox name of a move action if this action is selected. Otherwise it returns an empty string.
Returns:
mailbox name
See also:
setMailBox
mailbox
Definition at line 223 of file filtersetupitem.cpp.
References action, CONFIG_VALUE_FILTER_ACTION_MOVE, and mailbox.
Referenced by FilterSetupDialog::fillDialog().
void FilterSetupItem::setCriteriaLinkage (int linkage)
Sets the criteria linkage. Valid values are CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ALL (all criterias have to satisy) or CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ANY (at least one criteria has to satisy).
Parameters:
linkage criteria linkage
See also:
linkage
Definition at line 184 of file filtersetupitem.cpp.
References CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ALL, CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ANY, and DEFAULT_FILTER_CRITERIA_LINKAGE.
Referenced by init(), load(), and FilterSetupDialog::slotButtonClicked().
int FilterSetupItem::getCriteriaLinkage () const
Returns the criteria linkage. Possible values are CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ALL (all criterias have to satisy) or CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ANY (at least one criteria has to satisy).
Returns:
criteria linkage
See also:
setCriteriaLinkage
linkage
Definition at line 213 of file filtersetupitem.cpp.
References linkage.
Referenced by FilterSetupDialog::fillDialog().
void FilterSetupItem::setCriteriaList (FilterCriteriaList_Type list)
Sets the criteria list.
Parameters:
list criteria list
See also:
criteriaList
getCriteriaList
Types::FilterCriteriaList_Type
Definition at line 200 of file filtersetupitem.cpp.
References criteriaList.
Referenced by FilterSetupDialog::slotButtonClicked().
FilterCriteriaList_Type FilterSetupItem::getCriteriaList () const
Returns the criteria list.
Returns:
criteria list
See also:
criteriaList
setCriteriaList
Types::FilterCriteriaList_Type
Definition at line 231 of file filtersetupitem.cpp.
References criteriaList.
Referenced by FilterSetupDialog::fillDialog().
void FilterSetupItem::save ()
Saves the settings to the configuration file. The group is named CONFIG_GROUP_FILTER + filter number, e.g. Filter12.
Definition at line 99 of file filtersetupitem.cpp.
References action, config, CONFIG_ENTRY_FILTER_ACTION, CONFIG_ENTRY_FILTER_CRITERIA_CASESENSITIVE, CONFIG_ENTRY_FILTER_CRITERIA_CONDITION, CONFIG_ENTRY_FILTER_CRITERIA_LINKAGE, CONFIG_ENTRY_FILTER_CRITERIA_NUMBER, CONFIG_ENTRY_FILTER_CRITERIA_SOURCE, CONFIG_ENTRY_FILTER_CRITERIA_VALUE, CONFIG_ENTRY_FILTER_MOVE_MAILBOX, CONFIG_ENTRY_FILTER_NAME, CONFIG_GROUP_FILTER, CONFIG_VALUE_FILTER_ACTION_DELETE, CONFIG_VALUE_FILTER_ACTION_IGNORE, CONFIG_VALUE_FILTER_ACTION_MARK, CONFIG_VALUE_FILTER_ACTION_MOVE, CONFIG_VALUE_FILTER_ACTION_PASS, CONFIG_VALUE_FILTER_ACTION_SPAMCHECK, CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ALL, CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ANY, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_ACCOUNT, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_FROM, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_HEADER, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_SIZE, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_SUBJECT, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_TO, criteriaList, DEFAULT_FILTER_ACTION, DEFAULT_FILTER_CRITERIA_LINKAGE, linkage, mailbox, name, and number.
int FilterSetupItem::compare (FilterSetupItem * i, int col, bool ascending) const [virtual]
Compares this item to i using the column col in ascending order. Reutrns <0 if this item is less than i, 0 if they are equal and >0 if this item is greater than i. The parameter ascneding will be ignored.
Parameters:
i pointer to the second view item
col number of the sorted column
ascending ignored
Definition at line 241 of file filtersetupitem.cpp.
References ColNumber, and compare().
Referenced by compare().
void FilterSetupItem::load ()
Reads the settings from the config file. The group is named CONFIG_GROUP_FILTER + filter number, e.g. Filter12.
Definition at line 282 of file filtersetupitem.cpp.
References action, Types::FilterCriteria_Type::condition, config, CONFIG_ENTRY_FILTER_ACTION, CONFIG_ENTRY_FILTER_CRITERIA_CASESENSITIVE, CONFIG_ENTRY_FILTER_CRITERIA_CONDITION, CONFIG_ENTRY_FILTER_CRITERIA_LINKAGE, CONFIG_ENTRY_FILTER_CRITERIA_NUMBER, CONFIG_ENTRY_FILTER_CRITERIA_SOURCE, CONFIG_ENTRY_FILTER_CRITERIA_VALUE, CONFIG_ENTRY_FILTER_MOVE_MAILBOX, CONFIG_ENTRY_FILTER_NAME, CONFIG_GROUP_FILTER, CONFIG_VALUE_FILTER_ACTION_DELETE, CONFIG_VALUE_FILTER_ACTION_IGNORE, CONFIG_VALUE_FILTER_ACTION_MARK, CONFIG_VALUE_FILTER_ACTION_MOVE, CONFIG_VALUE_FILTER_ACTION_PASS, CONFIG_VALUE_FILTER_ACTION_SPAMCHECK, CONFIG_VALUE_FILTER_CRITERIA_COND_NUM_EQUAL, CONFIG_VALUE_FILTER_CRITERIA_COND_NUM_GREATER, CONFIG_VALUE_FILTER_CRITERIA_COND_NUM_GREATER_EQUAL, CONFIG_VALUE_FILTER_CRITERIA_COND_NUM_LESS, CONFIG_VALUE_FILTER_CRITERIA_COND_NUM_LESS_EQUAL, CONFIG_VALUE_FILTER_CRITERIA_COND_NUM_NOT_EQUAL, CONFIG_VALUE_FILTER_CRITERIA_COND_TEXT_CONTAINS, CONFIG_VALUE_FILTER_CRITERIA_COND_TEXT_EQUALS, CONFIG_VALUE_FILTER_CRITERIA_COND_TEXT_NOT_CONTAINS, CONFIG_VALUE_FILTER_CRITERIA_COND_TEXT_NOT_EQUALS, CONFIG_VALUE_FILTER_CRITERIA_COND_TEXT_NOT_REGEXPR, CONFIG_VALUE_FILTER_CRITERIA_COND_TEXT_REGEXPR, CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ALL, CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ANY, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_ACCOUNT, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_FROM, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_HEADER, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_SIZE, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_SUBJECT, CONFIG_VALUE_FILTER_CRITERIA_SOURCE_TO, criteriaList, Types::FilterCriteria_Type::cs, DEFAULT_FILTER_ACTION, DEFAULT_FILTER_ACTION_MOVE_MAILBOX, DEFAULT_FILTER_CRITERIA_CASE_SENSITIVE, DEFAULT_FILTER_CRITERIA_COND_NUM, DEFAULT_FILTER_CRITERIA_COND_TEXT, DEFAULT_FILTER_CRITERIA_LINKAGE, DEFAULT_FILTER_CRITERIA_SIZE, DEFAULT_FILTER_CRITERIA_SOURCE, DEFAULT_FILTER_NAME, linkage, number, Types::FilterCriteria_Type::numValue, setAction(), setCriteriaLinkage(), setMailBox(), setName(), Types::FilterCriteria_Type::source, and Types::FilterCriteria_Type::txtValue.
Referenced by ConfigFilter::load().
void FilterSetupItem::init () [protected]
Initializes the object.
Definition at line 42 of file filtersetupitem.cpp.
References ColNumber, config, DEFAULT_FILTER_ACTION, DEFAULT_FILTER_CRITERIA_LINKAGE, DEFAULT_FILTER_NAME, number, setAction(), setCriteriaLinkage(), and setName().
Referenced by FilterSetupItem().
void FilterSetupItem::updateActionColumn () [protected]
Updates the text of the rule column.
Definition at line 262 of file filtersetupitem.cpp.
References action, ColAction, CONFIG_VALUE_FILTER_ACTION_DELETE, CONFIG_VALUE_FILTER_ACTION_IGNORE, CONFIG_VALUE_FILTER_ACTION_MARK, CONFIG_VALUE_FILTER_ACTION_MOVE, CONFIG_VALUE_FILTER_ACTION_PASS, CONFIG_VALUE_FILTER_ACTION_SPAMCHECK, and mailbox.
Referenced by setAction(), and setMailBox().
Member Data Documentation
QString FilterSetupItem::name [private]
filter name
Definition at line 196 of file filtersetupitem.h.
Referenced by getName(), and save().
KSharedConfigPtr FilterSetupItem::config [private]
Connector to the configuration file
Definition at line 201 of file filtersetupitem.h.
Referenced by init(), load(), and save().
FilterCriteriaList_Type FilterSetupItem::criteriaList [private]
List of filter criterias.
Definition at line 206 of file filtersetupitem.h.
Referenced by getCriteriaList(), load(), save(), and setCriteriaList().
int FilterSetupItem::action [private]
Filter Action See constants.h for valid values (CONFIG_VALUE_FILTER_ACTION...).
Definition at line 212 of file filtersetupitem.h.
Referenced by getAction(), getMailBox(), load(), save(), and updateActionColumn().
QString FilterSetupItem::mailbox [private]
Contains the mailbox name if the move action is selected.
Definition at line 217 of file filtersetupitem.h.
Referenced by getMailBox(), save(), and updateActionColumn().
uint FilterSetupItem::number [private]
Filter Number. The filters will be showed and run through in ascending order. The first number is "0".
Definition at line 223 of file filtersetupitem.h.
Referenced by FilterSetupItem(), getNumber(), init(), load(), and save().
int FilterSetupItem::linkage [private]
Criteria Linkage. Valid values are CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ALL (all criterias have to satisy) or CONFIG_VALUE_FILTER_CRITERIA_LINKAGE_MATCH_ANY (at least one criteria has to satisy).
Definition at line 229 of file filtersetupitem.h.
Referenced by getCriteriaLinkage(), load(), and save().
The documentation for this class was generated from the following files:
src/filtersetupitem.h
src/filtersetupitem.cpp