KShowmail: KShowmailView Class Reference
KShowmailView Class Reference
Main view of KShowmail.
#include <kshowmailview.h>
Public Member Functions
KShowmailView (AccountViewModel *accountModel, MailViewModel *mailModel, QItemSelectionModel *mailSelectModel, QItemSelectionModel *accountSelectModel, QWidget *parent=0)
~KShowmailView ()
void refreshViews (QItemSelectionModel *mailSelectModel)
void saveSetup ()
void loadSetup ()
void addActionToAccountList (KAction *action)
void addActionToMailList (KAction *action)
Private Attributes
QTreeView * viewAccounts
QTreeView * viewMails
MailViewModel * mailModel
AccountViewModel * accountModel
Detailed Description
Main view of KShowmail.
It contains the account view and the mail view.
Definition at line 42 of file kshowmailview.h.
Constructor & Destructor Documentation
KShowmailView::KShowmailView (AccountViewModel * accountModel, MailViewModel * mailModel, QItemSelectionModel * mailSelectModel, QItemSelectionModel * accountSelectModel, QWidget * parent = 0)
Constructor
Parameters:
accountModel model for the account view
mailModel model for the mail view
mailSelectModel selection model of the mail view model
accountSelectModel selection model of the account view model
parent pointer to parent widget
Definition at line 21 of file kshowmailview.cpp.
References loadSetup(), viewAccounts, and viewMails.
KShowmailView::~KShowmailView ()
Destructor
Definition at line 55 of file kshowmailview.cpp.
Member Function Documentation
void KShowmailView::refreshViews (QItemSelectionModel * mailSelectModel)
Refreshes the account and mail view. Marks filtered mails.
Parameters:
mailSelectModel mail selection model
Definition at line 57 of file kshowmailview.cpp.
References accountModel, MailViewModel::getMarkedMails(), mailModel, MailViewModel::refresh(), AccountViewModel::refresh(), viewAccounts, and viewMails.
Referenced by KShowmail::KShowmail(), KShowmail::slotConfChanged(), and KShowmail::slotRefreshReady().
void KShowmailView::saveSetup ()
Saves the column widths
Definition at line 75 of file kshowmailview.cpp.
References accountModel, CONFIG_ENTRY_WIDTH_ACCOUNT_ACCOUNT, CONFIG_ENTRY_WIDTH_ACCOUNT_ACTIVE, CONFIG_ENTRY_WIDTH_ACCOUNT_MESSAGES, CONFIG_ENTRY_WIDTH_ACCOUNT_SERVER, CONFIG_ENTRY_WIDTH_ACCOUNT_SIZE, CONFIG_ENTRY_WIDTH_ACCOUNT_USER, CONFIG_ENTRY_WIDTH_MESSAGE_ACCOUNT, CONFIG_ENTRY_WIDTH_MESSAGE_CONTENT, CONFIG_ENTRY_WIDTH_MESSAGE_DATE, CONFIG_ENTRY_WIDTH_MESSAGE_FROM, CONFIG_ENTRY_WIDTH_MESSAGE_NUMBER, CONFIG_ENTRY_WIDTH_MESSAGE_SIZE, CONFIG_ENTRY_WIDTH_MESSAGE_STATE, CONFIG_ENTRY_WIDTH_MESSAGE_SUBJECT, CONFIG_ENTRY_WIDTH_MESSAGE_TO, CONFIG_GROUP_ACCOUNT_LIST, CONFIG_GROUP_MESSAGE_LIST, mailModel, MailViewModel::saveSetup(), AccountViewModel::saveSetup(), viewAccounts, and viewMails.
Referenced by KShowmail::queryClose(), and KShowmail::slotSetup().
void KShowmailView::loadSetup ()
Loads and sets the column widths
Definition at line 138 of file kshowmailview.cpp.
References CONFIG_ENTRY_DISPLAY_ACCOUNT_ACCOUNT, CONFIG_ENTRY_DISPLAY_ACCOUNT_ACTIVE, CONFIG_ENTRY_DISPLAY_ACCOUNT_MESSAGES, CONFIG_ENTRY_DISPLAY_ACCOUNT_SERVER, CONFIG_ENTRY_DISPLAY_ACCOUNT_SIZE, CONFIG_ENTRY_DISPLAY_ACCOUNT_USER, CONFIG_ENTRY_DISPLAY_MESSAGE_ACCOUNT, CONFIG_ENTRY_DISPLAY_MESSAGE_CONTENT, CONFIG_ENTRY_DISPLAY_MESSAGE_DATE, CONFIG_ENTRY_DISPLAY_MESSAGE_FROM, CONFIG_ENTRY_DISPLAY_MESSAGE_NUMBER, CONFIG_ENTRY_DISPLAY_MESSAGE_SIZE, CONFIG_ENTRY_DISPLAY_MESSAGE_STATE, CONFIG_ENTRY_DISPLAY_MESSAGE_SUBJECT, CONFIG_ENTRY_DISPLAY_MESSAGE_TO, CONFIG_ENTRY_SORT_COLUMN_ACCOUNT, CONFIG_ENTRY_SORT_COLUMN_MESSAGE, CONFIG_ENTRY_SORT_ORDER_ACCOUNT, CONFIG_ENTRY_SORT_ORDER_MESSAGE, CONFIG_ENTRY_WIDTH_ACCOUNT_ACCOUNT, CONFIG_ENTRY_WIDTH_ACCOUNT_ACTIVE, CONFIG_ENTRY_WIDTH_ACCOUNT_MESSAGES, CONFIG_ENTRY_WIDTH_ACCOUNT_SERVER, CONFIG_ENTRY_WIDTH_ACCOUNT_SIZE, CONFIG_ENTRY_WIDTH_ACCOUNT_USER, CONFIG_ENTRY_WIDTH_MESSAGE_ACCOUNT, CONFIG_ENTRY_WIDTH_MESSAGE_CONTENT, CONFIG_ENTRY_WIDTH_MESSAGE_DATE, CONFIG_ENTRY_WIDTH_MESSAGE_FROM, CONFIG_ENTRY_WIDTH_MESSAGE_NUMBER, CONFIG_ENTRY_WIDTH_MESSAGE_SIZE, CONFIG_ENTRY_WIDTH_MESSAGE_STATE, CONFIG_ENTRY_WIDTH_MESSAGE_SUBJECT, CONFIG_ENTRY_WIDTH_MESSAGE_TO, CONFIG_GROUP_ACCOUNT_LIST, CONFIG_GROUP_MESSAGE_LIST, CONFIG_GROUP_VIEW, CONFIG_VALUE_SORT_ORDER_DESCENDING, DEFAULT_DISPLAY_ACCOUNT_ACCOUNT, DEFAULT_DISPLAY_ACCOUNT_ACTIVE, DEFAULT_DISPLAY_ACCOUNT_MESSAGES, DEFAULT_DISPLAY_ACCOUNT_SERVER, DEFAULT_DISPLAY_ACCOUNT_SIZE, DEFAULT_DISPLAY_ACCOUNT_USER, DEFAULT_DISPLAY_MESSAGE_STATE, DEFAULT_SORT_COLUMN_ACCOUNT, DEFAULT_SORT_COLUMN_MESSAGE, DEFAULT_SORT_ORDER, DEFAULT_WIDTH_ACCOUNT_ACCOUNT, DEFAULT_WIDTH_ACCOUNT_ACTIVE, DEFAULT_WIDTH_ACCOUNT_MESSAGES, DEFAULT_WIDTH_ACCOUNT_SERVER, DEFAULT_WIDTH_ACCOUNT_SIZE, DEFAULT_WIDTH_ACCOUNT_USER, DEFAULT_WIDTH_MESSAGE_ACCOUNT, DEFAULT_WIDTH_MESSAGE_CONTENT, DEFAULT_WIDTH_MESSAGE_DATE, DEFAULT_WIDTH_MESSAGE_FROM, DEFAULT_WIDTH_MESSAGE_NUMBER, DEFAULT_WIDTH_MESSAGE_SIZE, DEFAULT_WIDTH_MESSAGE_STATE, DEFAULT_WIDTH_MESSAGE_SUBJECT, DEFAULT_WIDTH_MESSAGE_TO, viewAccounts, and viewMails.
Referenced by KShowmail::KShowmail(), KShowmailView(), and KShowmail::slotConfChanged().
void KShowmailView::addActionToAccountList (KAction * action)
Adds an action to the account view context menu
Parameters:
action action to add
Definition at line 209 of file kshowmailview.cpp.
References viewAccounts.
Referenced by KShowmail::KShowmail().
void KShowmailView::addActionToMailList (KAction * action)
Adds an action to the mail view context menu
Parameters:
action action to add
Definition at line 215 of file kshowmailview.cpp.
References viewMails.
Referenced by KShowmail::KShowmail().
Member Data Documentation
QTreeView* KShowmailView::viewAccounts [private]
account list
Definition at line 96 of file kshowmailview.h.
Referenced by addActionToAccountList(), KShowmailView(), loadSetup(), refreshViews(), and saveSetup().
QTreeView* KShowmailView::viewMails [private]
mail list
Definition at line 101 of file kshowmailview.h.
Referenced by addActionToMailList(), KShowmailView(), loadSetup(), refreshViews(), and saveSetup().
MailViewModel* KShowmailView::mailModel [private]
Mail view model
Definition at line 106 of file kshowmailview.h.
Referenced by refreshViews(), and saveSetup().
AccountViewModel* KShowmailView::accountModel [private]
Account view model
Definition at line 111 of file kshowmailview.h.
Referenced by refreshViews(), and saveSetup().
The documentation for this class was generated from the following files:
src/kshowmailview.h
src/kshowmailview.cpp