KShowmail: MailBoxWizard Class Reference
MailBoxWizard Class Reference
Wizard to configure the mailbox to which a filteres mail shall be moved.
#include <mailboxwizard.h>
Public Member Functions
MailBoxWizard (QWidget *parent=0)
~MailBoxWizard ()
QString getPath ()
Private Slots
void slotOpenDirDialog ()
void slotPageChanged (int pageID)
Private Member Functions
bool isMailDir (const QDir &path)
void addMailBoxListItem (QString boxname, QDir path)
Private Attributes
KLineEdit * txtMailDir
KPushButton * btnMailDir
QTreeWidget * lstMailboxes
Detailed Description
Wizard to configure the mailbox to which a filteres mail shall be moved.
Author:
Ulrich Weigelt <ulrich.weigelt@gmx.de>
Definition at line 51 of file mailboxwizard.h.
Constructor & Destructor Documentation
MailBoxWizard::MailBoxWizard (QWidget * parent = 0)
Constructor
Definition at line 20 of file mailboxwizard.cpp.
References btnMailDir, lstMailboxes, slotOpenDirDialog(), slotPageChanged(), and txtMailDir.
MailBoxWizard::~MailBoxWizard ()
Destructor
Definition at line 64 of file mailboxwizard.cpp.
Member Function Documentation
QString MailBoxWizard::getPath ()
Returns the absolute path of the selected mailbox.
Returns:
the path
Definition at line 163 of file mailboxwizard.cpp.
References MailBoxWizardListItem::getPath(), and lstMailboxes.
bool MailBoxWizard::isMailDir (const QDir & path) [private]
Returns whether the given directory is a maildir directory
Parameters:
path the directory for test
Returns:
TRUE - directory is a maildir directory
Definition at line 112 of file mailboxwizard.cpp.
Referenced by slotPageChanged().
void MailBoxWizard::addMailBoxListItem (QString boxname, QDir path) [private]
Adds a new mailbox list view item to the mailbox list or to a given parent item.
Parameters:
boxname name of the mailbox
path path to the directory of this mailbox
Definition at line 139 of file mailboxwizard.cpp.
References lstMailboxes.
Referenced by slotPageChanged().
void MailBoxWizard::slotOpenDirDialog () [private, slot]
Connected with btnMailDir. Opens a file dialog to choose the mail directory.
Definition at line 68 of file mailboxwizard.cpp.
References txtMailDir.
Referenced by MailBoxWizard().
void MailBoxWizard::slotPageChanged (int pageID) [private, slot]
Connected with the signal selected of this wizard. Searchs for mailboxes inside the path typed in page1.
Parameters:
pageID ID of the showed page
Definition at line 83 of file mailboxwizard.cpp.
References addMailBoxListItem(), isMailDir(), lstMailboxes, and txtMailDir.
Referenced by MailBoxWizard().
Member Data Documentation
KLineEdit* MailBoxWizard::txtMailDir [private]
This contains the path to the mail directory
Definition at line 79 of file mailboxwizard.h.
Referenced by MailBoxWizard(), slotOpenDirDialog(), and slotPageChanged().
KPushButton* MailBoxWizard::btnMailDir [private]
This button opens a file dialog to slecht the mail directory
Definition at line 84 of file mailboxwizard.h.
Referenced by MailBoxWizard().
QTreeWidget* MailBoxWizard::lstMailboxes [private]
This view shows the available mailboxes in the selected directory
Definition at line 89 of file mailboxwizard.h.
Referenced by addMailBoxListItem(), getPath(), MailBoxWizard(), and slotPageChanged().
The documentation for this class was generated from the following files:
src/mailboxwizard.h
src/mailboxwizard.cpp