KShowmail: ConfigAccounts Class Reference
ConfigAccounts Class Reference
Part of the setup dialog (KShowMailApp::SetupDialog) to configure the accounts.
#include <configaccounts.h>
Public Member Functions
ConfigAccounts (QWidget *parent=0, const QVariantList &args=QVariantList())
~ConfigAccounts ()
virtual void load ()
virtual void defaults ()
virtual void save ()
Private Slots
void slotChanged ()
void slotAdd ()
void slotEdit ()
void slotRemove ()
Private Attributes
KSharedConfigPtr config
QTreeWidget * accountListView
KPushButton * btnAdd
KPushButton * btnEdit
KPushButton * btnRemove
Detailed Description
Part of the setup dialog (KShowMailApp::SetupDialog) to configure the accounts.
Author:
Ulrich Weigelt <ulrich.weigelt@gmx.de>
Definition at line 44 of file configaccounts.h.
Constructor & Destructor Documentation
ConfigAccounts::ConfigAccounts (QWidget * parent = 0, const QVariantList & args = QVariantList()) [explicit]
Generic Constructor
ConfigAccounts::~ConfigAccounts ()
Destructor
Definition at line 68 of file configaccounts.cpp.
Member Function Documentation
void ConfigAccounts::load () [virtual]
Overloaded method of KCModule. Sets the user interface elements to reflect the current settings stored in the config file.
Definition at line 72 of file configaccounts.cpp.
References accountListView, config, CONFIG_ENTRY_ACCOUNTS_LIST, CONFIG_GROUP_ACCOUNTS, and AccountSetupItem::load().
void ConfigAccounts::defaults () [virtual]
Overloaded method of KCModule. Sets the user interface elements to default values. This method is called when the user clicks the "Default" button.
Definition at line 138 of file configaccounts.cpp.
void ConfigAccounts::save () [virtual]
Overloaded method of KCModule. Stores the config information as shown in the user interface in the config file. Is called when the user clicks "Apply" or "Ok".
Definition at line 90 of file configaccounts.cpp.
References accountListView, config, CONFIG_ENTRY_ACCOUNTS_LIST, CONFIG_GROUP_ACCOUNTS, AccountSetupItem::getAccountName(), and AccountSetupItem::save().
void ConfigAccounts::slotChanged () [private, slot]
Connected with the configuration items. Calls the slot changed() of KCModule to notify the dialog about the change.
Definition at line 142 of file configaccounts.cpp.
Referenced by slotAdd(), slotEdit(), and slotRemove().
void ConfigAccounts::slotAdd () [private, slot]
Connected with button btnAdd. Opens the account setup dialog with an account item pointer of NULL. If the user has clicked OK, the dialog will create a new account item with the entered values and adds it to the list view.
Definition at line 147 of file configaccounts.cpp.
References accountListView, and slotChanged().
void ConfigAccounts::slotEdit () [private, slot]
Connected with button btnEdit. Opens the account setup with the selected account item.
Definition at line 161 of file configaccounts.cpp.
References accountListView, and slotChanged().
void ConfigAccounts::slotRemove () [private, slot]
Connected with button btnRemove. Removes the selected item.
Definition at line 182 of file configaccounts.cpp.
References accountListView, AccountSetupItem::getAccountName(), and slotChanged().
Member Data Documentation
KSharedConfigPtr ConfigAccounts::config [private]
Connector to the configuration file
Definition at line 87 of file configaccounts.h.
Referenced by load(), and save().
QTreeWidget* ConfigAccounts::accountListView [private]
Account List View
Definition at line 92 of file configaccounts.h.
Referenced by load(), save(), slotAdd(), slotEdit(), and slotRemove().
KPushButton* ConfigAccounts::btnAdd [private]
Button to add a new account
Definition at line 97 of file configaccounts.h.
KPushButton* ConfigAccounts::btnEdit [private]
Button to edit an account
Definition at line 102 of file configaccounts.h.
KPushButton* ConfigAccounts::btnRemove [private]
Button to remove an account
Definition at line 107 of file configaccounts.h.
The documentation for this class was generated from the following files:
src/configaccounts.h
src/configaccounts.cpp