KShowmail: POP3Constants Namespace Reference
POP3Constants Namespace Reference
Constants of the POP3 protocol.
Functions
static const QString RESPONSE_POSITIVE ("+OK")
positive server response
static const QString RESPONSE_NEGATIVE ("-ERR")
negative server response
static const QString END_MULTILINE_RESPONSE (".")
End of multi-line response.
static const QString CAPA_REQUEST ("CAPA")
Capabilities request.
static const QString AUTH_REQUEST ("AUTH")
Authentication mechanism request.
static const QString CAPA_RESPONSE_STLS ("STLS")
Capabilities response STLS available.
static const QString START_TLS ("STLS")
command for start TLS
static const QString COMMIT ("QUIT")
Commit command.
static const QString LOGIN_USER ("USER")
Sends the username for login.
static const QString LOGIN_PASSWD ("PASS")
Sends the password for login.
static const QString LOGIN_APOP ("APOP")
Command for login using APOP.
static const QString UID_LIST ("UIDL")
Command to get the UID list.
static const QString MAIL_LIST ("LIST")
Command to get a list of mail numbers and sizes.
static const QString GET_HEADER ("TOP")
This command gets the header of a mail.
static const QString DELETE ("DELE")
Deletes a mail.
static const QString GET_MAIL ("RETR")
Get a mail.
Detailed Description
Constants of the POP3 protocol.
Function Documentation
static const QString POP3Constants::AUTH_REQUEST ("AUTH") [static]
Authentication mechanism request.
Referenced by Account::getAuthMech().
static const QString POP3Constants::CAPA_REQUEST ("CAPA") [static]
Capabilities request.
Referenced by Account::getCapabilities().
static const QString POP3Constants::CAPA_RESPONSE_STLS ("STLS") [static]
Capabilities response STLS available.
Referenced by Account::slotCapabilitiesResponse().
static const QString POP3Constants::COMMIT ("QUIT") [static]
Commit command.
Referenced by Account::commit(), Account::commitBeforeRefresh(), and Account::slotCommitResponse().
static const QString POP3Constants::DELETE ("DELE") [static]
Deletes a mail.
Referenced by Account::deleteNextMail().
static const QString POP3Constants::END_MULTILINE_RESPONSE (".") [static]
End of multi-line response.
Referenced by Account::readfromSocket(), and Account::removeEndOfResponseMarker().
static const QString POP3Constants::GET_HEADER ("TOP") [static]
This command gets the header of a mail.
Referenced by Account::getNextHeader().
static const QString POP3Constants::GET_MAIL ("RETR") [static]
Get a mail.
Referenced by Account::getNextMailForDownloadActions(), and Account::showNextMail().
static const QString POP3Constants::LOGIN_APOP ("APOP") [static]
Command for login using APOP.
Referenced by Account::loginApop().
static const QString POP3Constants::LOGIN_PASSWD ("PASS") [static]
Sends the password for login.
Referenced by Account::loginPasswd().
static const QString POP3Constants::LOGIN_USER ("USER") [static]
Sends the username for login.
Referenced by Account::loginUser().
static const QString POP3Constants::MAIL_LIST ("LIST") [static]
Command to get a list of mail numbers and sizes.
Referenced by Account::getMailSizes(), and Account::slotMailSizesResponse().
static const QString POP3Constants::RESPONSE_NEGATIVE ("-ERR") [static]
negative server response
Referenced by Account::isNegativeResponse(), and Account::removeStatusIndicator().
static const QString POP3Constants::RESPONSE_POSITIVE ("+OK") [static]
positive server response
Referenced by Account::isPositiveServerMessage(), and Account::removeStatusIndicator().
static const QString POP3Constants::START_TLS ("STLS") [static]
command for start TLS
Referenced by Account::startTLS().
static const QString POP3Constants::UID_LIST ("UIDL") [static]
Command to get the UID list.
Referenced by Account::getUIDList().